---
title: "Integration of donor only and with lab"
date: "2024-01-05"
author: "Jesse Rop"
output:
  html_document:
    toc: true
    theme: united
    code_folding: hide
    df_print: paged
---

```{r}
suppressPackageStartupMessages({
  library(Seurat)
  # library(sctransform)
  # library(rgl)
  library(ggrepel)
  # library(ggpubr)
  library(dplyr) 
  library(stringr)
  library(purrr)
  library(readr)
  library(tibble)
  library(ggplot2)
  # library(ggnewscale)
  library(tidyr)
  library(cowplot)
  # library(scDblFinder)
  library(SeuratData)
  library(SeuratDisk)
  # library(scmap)
  library(SingleCellExperiment)
  library(pheatmap)
  library(plotly)
  # library(Hmisc)
  # library(rmarkdown)
  library(RColorBrewer)
  # library(MAST)
  library(ggvenn)
  # library("biomaRt")
  library(conflicted)
  # library(SoupX)
  library(MetBrewer)
  # library(dreamlet)
  # library(muscat)
  # library(ExperimentHub)
  # library(zenith)
  library(scater)
  library(slingshot)
  library(harmony)
  library(ggforce)
  # library(miloR)
  library(scater)
  library(scran)
  library(patchwork)
  # library(scRNAseq)
  library(scuttle)
  library(irlba)
  library(BiocParallel)
  library(tradeSeq)
  library(ComplexHeatmap)
  library(circlize)
  conflict_prefer("select", "dplyr")
  conflict_prefer("filter", "dplyr")
  conflict_prefer("rename", "dplyr")
  conflicts_prefer(dplyr::count)
  conflicts_prefer(base::as.data.frame)
  
})
```


```{r setup}
sample_set = "Mali2"

# knitr::opts_knit$set(root.dir = paste0("/Users/jr35/Google Drive/My Drive/PHD_documents/malaria_phd/", sample_set))
knitr::opts_knit$set(root.dir = paste0("/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/", sample_set))
```


#  integration of all MSC

### Common functions

#### Source commong functions, varriables and tables
```{r}
##Boxplot labeling function
source("../multipurpose_scripts_lnk/seurat_sce/seu_sce_common_fns.R")
source("../multipurpose_scripts_lnk/plotting_common_fns.R")
source("/nfs/users/nfs_j/jr35/Mali2/mali22_code/pf_common_vars.R")
```



```{r}
obj_names = c('M55', 'no_M55', 'no_M55_all_gns', 'asex_allgns', 'fem_allgns', 'male_allgns')

```

#####!!! DE below in seurat. Already done using scvi. Not sure which one to go with


```{r}
all_jcC_seu_scvi <- readRDS("data/processed/Pf/m2_all/scvi2seu/all_jcC_seu_scvino_M55.RDS")))

```

```{r}
# stg_names = c('Female', 'Male', 'Asexual')

```


```{r}
all_jcC_seu_scvi_stg_noM55_afm <- SplitObject(all_jcC_seu_scvi[["no_M55"]], split.by= "stage_afm")
```

```{r}
map(all_jcC_seu_scvi_stg_noM55_afm, ~.x@meta.data %>% count(stage_afm, leiden) %>% arrange(desc(n)))
```

```{r}
map(all_jcC_seu_scvi_stg_noM55_afm, ~.x@meta.data %>% count(leiden) %>% arrange(desc(n)))

```

```{r}
clusters2keep4DE <- map(all_jcC_seu_scvi_stg_noM55_afm, ~.x@meta.data %>% count(leiden) %>% arrange(desc(n)) %>% filter(n>150) %>% pull(leiden))

```

```{r, fig.height=6, fig.width=10}
## Highlight likely misplaced clusters to remove
map2(all_jcC_seu_scvi_stg_noM55_afm, clusters2keep4DE, ~DimPlot(.x, reduction = "scvi_umap", pt.size = 0.01, cells.highlight = colnames(.x[,!.x$leiden %in% .y])))
```

```{r}
all_jcC_seu_scvi_stg_noM55_afm <- map2(all_jcC_seu_scvi_stg_noM55_afm, clusters2keep4DE, ~subset(.x, subset = leiden %in% .y))
```

```{r}
map(all_jcC_seu_scvi_stg_noM55_afm, ~.x@meta.data %>% count(leiden) %>% arrange(desc(n)))
```

```{r}
DimPlot(all_jcC_seu_scvi[["no_M55"]], group.by = "leiden", reduction = "scvi_umap", label = T)

```

```{r}
map(all_jcC_seu_scvi_stg_noM55_afm, ~.x@meta.data %>% count(stage_afm, leiden, orig.ident) %>% group_by(leiden) %>% arrange(desc(n), .by_group = T) %>% filter(n>50))

```

```{r}
all_jcC_seu_scvi_stg_noM55_afm <- map(all_jcC_seu_scvi_stg_noM55_afm, ~SetIdent(.x, value = "leiden"))

```


```{r}
seu_scviLeiden_markers <- map(all_jcC_seu_scvi_stg_noM55_afm, ~FindAllMarkers(.x ))
```


```{r, warning=FALSE, message=FALSE}
seu_scviLeiden_markers_anot <- map(seu_scviLeiden_markers, ~.x %>%  left_join(., Pf3D7_genes_plasmoDB[,c("gene_id", "Gene")], by = c("gene" = "gene_id")))

# seu_scviLeiden_markers_anot
```


```{r}
# saveRDS(seu_scviLeiden_markers_anot, "data/processed/Pf/m2_all/seu_scviLeiden_markers_anot.RDS")
saveRDS(seu_scviLeiden_markers_anot, "data/processed/Pf/m2_all/scvi2seu/seu_scviLeiden_markers_anot3.RDS")

```

```{r, eval=FALSE}
## Read in DE results
seu_scviLeiden_markers_anot readRDS("data/processed/Pf/m2_all/scvi2seu/seu_scviLeiden_markers_anot3.RDS")

```


```{r}
map(all_jcC_seu_scvi_stg_noM55_afm, ~FeaturePlot(.x, features = "nFeature_RNA", reduction = "scvi_umap", label = T))
map(all_jcC_seu_scvi_stg_noM55_afm, ~DimPlot(.x, group.by = "leiden", reduction = "scvi_umap", label = T))

```

```{r}
DimPlot(all_jcC_seu_scvi[["no_M55"]], group.by = "leiden", reduction = "scvi_umap", label = T)

```

```{r, warning=FALSE, message=FALSE}
map(seu_scviLeiden_markers_anot2, ~.x %>% 
  # filter(gene %in% gns) %>% 
  arrange(desc(avg_log2FC)) %>% 
    filter(p_val_adj< 0.05 & avg_log2FC>0) %>%
    group_by(cluster) %>% 
    slice_min(order_by = p_val_adj, n = 30) %>% 
    slice_max(order_by = avg_log2FC, n = 10))
```

```{r}
map(all_jcC_seu_scvi, ~DimPlot(.x, group.by = "leiden", reduction = "scvi_umap", label = T))

```

```{r, fig.height=6, fig.width=10}
# kahrp
map(all_jcC_seu_scvi, ~FeaturePlot(.x, features = "PF3D7-0202000", reduction = "scvi_umap", pt.size = 0.01, raster = F, order = T))
```


```{r, warning=FALSE, message=FALSE}
map2(seu_scviLeiden_markers_anot[c("M55.Female", "no_M55.Female")], list(c("8"), c("9", "13", "10")), ~.x %>% 
  filter(cluster %in% .y) %>%
  arrange(desc(avg_log2FC)) %>% 
    filter(p_val_adj< 0.05 & avg_log2FC>0) %>%
    group_by(cluster) %>% 
    slice_min(order_by = p_val_adj, n = 10)%>% 
    slice_min(order_by = pct.2, n = 10))
```

Cluster 9 - activated like 

Gamete top marker - PF3D7_0825800 https://www.nature.com/articles/s41586-025-09653-0
Ngwa activated gametocytes https://opus.bibliothek.uni-wuerzburg.de/opus4-wuerzburg/frontdoor/deliver/index/docId/6822/file/PhD_thesis_Che_Julius_Ngwa_final.pdf

```{r, warning=FALSE, message=FALSE}
## Ngwa activated gametocytes https://opus.bibliothek.uni-wuerzburg.de/opus4-wuerzburg/frontdoor/deliver/index/docId/6822/file/PhD_thesis_Che_Julius_Ngwa_final.pdf
ngwa_up_activ_gam <- c("PF3D7_0827800", "Pf3D7_1246200", "PF3D7_1218800", "PF3D7_1239400", "PF3D7_0704100", "PF3D7_0417400", "PF3D7_1321000", "PF3D7_131670") %>% str_replace(., "_", "-")

map(seu_scviLeiden_markers_anot[c("M55.Female", "no_M55.Female")], ~.x %>% 
  filter(gene %in% ngwa_up_activ_gam) %>% 
    filter(p_val_adj< 0.05 & avg_log2FC>0) %>%
  arrange(desc(avg_log2FC)) )
```
```{r, warning=FALSE, message=FALSE}
## Gamete top marker - PF3D7_0825800 https://www.nature.com/articles/s41586-025-09653-0
map(all_jcC_seu_scvi, ~FeaturePlot(.x, features = c("PF3D7-0825800"), order =T, ncol = 1))

```

```{r, warning=FALSE, message=FALSE}
map2(seu_scviLeiden_markers_anot[c("M55.Asexual", "no_M55.Asexual")], list(c("18","21", "8"), c("14","20", "9")), ~.x %>% 
  filter(cluster %in% .y) %>%
  arrange(desc(avg_log2FC)) %>% 
    filter(p_val_adj< 0.05 & avg_log2FC>0) %>%
    group_by(cluster) %>% 
    slice_min(order_by = p_val_adj, n = 10))
```

```{r, warning=FALSE, message=FALSE, fig.width=16, fig.height=6}
map(all_jcC_seu_scvi_stg_noM55_afm[c("M55.Asexual", "no_M55.Asexual")], ~FeaturePlot(.x, features = c("PF3D7-0829900", "PF3D7-1229200", "PF3D7-1222600", "PF3D7-1102500", "PF3D7-0818900"), order =T, ncol = 3))

```

cold-activated noncoding RNAs Temperature Regulated Untranslated Lncrna (tru-lncRNA) 
https://www.sciencedirect.com/science/article/pii/S0378111923003578 
https://www.nature.com/articles/s41564-021-00940-w
https://pmc.ncbi.nlm.nih.gov/articles/PMC12235521/
https://onlinelibrary.wiley.com/doi/10.1111/1744-7917.13383
```{r, warning=FALSE, message=FALSE}
cold_activated_RNAs <- c("PF3D7-1148100", "PF3D7-1148200", "PF3D7-1148500", "PF3D7-1370500", "PF3D-1370800", "PF3D7-1370900")
```


```{r, fig.width=14, fig.height=8}
map(all_jcC_seu_scvi_stg_noM55_afm[c("M55.Asexual", "no_M55.Asexual")], ~FeaturePlot(.x, features = cold_activated_RNAs, order =T, ncol = 3))
```



```{r, warning=FALSE, message=FALSE}
map2(seu_scviLeiden_markers_anot[c("M55.Asexual", "no_M55.Asexual")], list(c("14","16", "17"), c("16","15", "10")), ~.x %>% 
  filter(cluster %in% .y) %>%
  arrange(desc(avg_log2FC)) %>% 
    filter(p_val_adj< 0.05 & avg_log2FC>0) %>%
    group_by(cluster) %>% 
    slice_min(order_by = p_val_adj, n = 30))
```