---
title: "MSC QC and preprocessing"
date: '2022-07-11'
author: 'Jesse Rop'
output:
  html_document:
    toc: true
    theme: united
    code_folding: hide
    df_print: paged
---

```{r}
suppressPackageStartupMessages({
  library(Seurat)
  library(sctransform)
  # library(rgl)
  library(patchwork)
  # library(DoubletFinder)
  library(ggrepel)
  library(ggpubr)
  library(dplyr) 
  library(stringr)
  library(purrr)
  library(readr)
  library(tibble)
  library(ggplot2)
  library(tidyr)
  library(cowplot)
  # library(scDblFinder)
  library(SeuratData)
  library(SeuratDisk)
  library(plotly)
  library(Hmisc)
  library(rmarkdown)
  library(RColorBrewer)
  # library(Platypus)
  library(ggvenn)
  library(conflicted)
  # library(SoupX)
  library(MetBrewer)
  library(ggh4x)
  library(SingleCellExperiment)
  # library(scmap)
  # library(ggsankey)
  # library(findPC)
  library(BPCells)
  # library(furrr)
  # library(future.batchtools)
  library(parallel)
  library(EnhancedVolcano)
  library(DropletUtils)
  library(ggforce)
  library(slingshot)
  
  conflict_prefer("select", "dplyr")
  conflict_prefer("filter", "dplyr")
  conflict_prefer("rename", "dplyr")
  conflict_prefer("map", "purrr")
  conflict_prefer("count", "dplyr")
  conflicts_prefer(base::saveRDS)
  conflicts_prefer(SingleCellExperiment::colData)
  conflicts_prefer(base::as.data.frame)
  conflicts_prefer(base::as.factor)
})
```

# MSC Preprocessing


## setup, read input files and exploratory visualizations and general functions


```{r, setup}
# library(reticulate)
# # use_condaenv("/Users/jr35/envs/scv_jupcon/", required = TRUE)
# # matplotlib <- reticulate::import("matplotlib")
# # matplotlib$use("Agg", force = TRUE)
# 
# knitr::opts_knit$set(root.dir = '/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/Mali')
knitr::opts_knit$set(root.dir = '/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/Mali2')

```

### Common functions

#### Source commong functions, varriables and tables
```{r}
##Boxplot labeling function
source("/nfs/users/nfs_j/jr35/multipurpose_scripts/seurat_sce/seu_sce_common_fns.R")
source("/nfs/users/nfs_j/jr35/multipurpose_scripts/plotting_common_fns.R")
source("/nfs/users/nfs_j/jr35/Mali2/mali22_code/pf_common_vars.R")
```


```{r, message=F, warning=F, eval=T}
## Get file list
fm_leiden_w_donors_norm_harmony_jnd_list_files <- Sys.glob("data/processed/Pf/m2_all/integration/fm_leiden_w_donors_*_norm_harmony_jnd.RDS")

fm_leiden_w_donors_norm_harmony_jnd_list_files
```

```{r, message=F, warning=F, eval=T}
## read filtered barcodes
fm_leiden_w_donors_norm_harmony_jnd <- map(fm_leiden_w_donors_norm_harmony_jnd_list_files, ~.x %>% 
  set_names(nm = (str_remove_all(.,'data/processed/Pf/m2_all/integration/fm_leiden_w_donors_|_norm_harmony_jnd.RDS')))) %>% 
  unlist(., recursive = F) %>% 
  # .[sample_name] %>%
  map(readRDS)

```


```{r, warning=FALSE, message=FALSE}
imap(fm_leiden_w_donors_norm_harmony_jnd, ~DimPlot(.x, label = T, reduction = "umap.harmony_PC_man", dims = c(1,2), group.by = "leiden") + labs(title = .y)) 

```


```{r, warning=FALSE, message=FALSE}
imap(fm_leiden_w_donors_norm_harmony_jnd, ~DimPlot(.x, label = T, reduction = "integrated.harmony_PC_man", dims = c(1,2), group.by = "leiden") + labs(title = .y)) 

```

```{r, warning=FALSE, message=FALSE}
# fm_leiden_w_donors_norm_harmony_jnd <- fm_leiden_w_donors_norm_harmony_jnd[c("all.fLE", "all.m", "w.5.f", "w.7.f", "w.7.m")]

fm_leiden_w_donors_norm_harmony_jnd_set <- fm_leiden_w_donors_norm_harmony_jnd[c("all.m_mLE", "w.5.f_fLE", "w.5.f_fLE_no_asx_dbt", "w.5.f", "w.5.f_no_asx_dbt", "w.7.f", "w.7.f_fLE", "w.7.m")]
# fm_leiden_w_donors_norm_harmony_jnd <- fm_leiden_w_donors_norm_harmony_jnd[c("w.5.f_no_asx_dbt")]

```

```{r, warning=FALSE, message=FALSE}
fm_leiden_w_donors_norm_harmony_jnd_set <- fm_leiden_w_donors_norm_harmony_jnd_set %>% 
  set_names(str_replace_all(names(fm_leiden_w_donors_norm_harmony_jnd_set), c("w\\." = "w_pt", "\\." = "_")))
```


```{r, warning=FALSE, message=FALSE}
imap(fm_leiden_w_donors_norm_harmony_jnd_set, ~DimPlot(.x, label = T, reduction = "umap.harmony_PC_man", dims = c(1,2), group.by = "leiden") + labs(title = .y)) 

```

Convert to h5ad for scvi
```{r, message=FALSE, warning=FALSE, eval=T}
## Convert to h5ad for scvi
imap(fm_leiden_w_donors_norm_harmony_jnd_set, ~{
  
  ## Join layers before conversion
  seu_jnd <- JoinLayers(.x, assay = "RNA", layers = "counts")
  
  # ## !!!NB - NEEDS SORTING IN FUTURE UPGRADING TO SEURAT 5 RESULTED IN ERROR AS DESCRIBED https://github.com/mojaveazure/seurat-disk/issues/147#top
  
  # seu_jnd[["RNA"]] <- CreateAssayObject(counts = seu_jnd[["RNA"]]$counts) #Convert Assay v5 to Assay
  # seu_jnd[["SCT"]] <- NULL
  seu_jnd[["RNA"]] <- CreateAssayObject(counts = seu_jnd[["RNA"]]$counts) #Convert Assay v5 to Assay
  # seu_jnd@meta.data <- .x@meta.data
    
  SaveH5Seurat(seu_jnd, filename =  paste0("data/processed/Pf/m2_all/integration/fm_harmony_", .y,".h5Seurat"), overwrite = T)
    
  Convert(paste0("data/processed/Pf/m2_all/integration/fm_harmony_", .y,".h5Seurat"), dest = "h5ad", overwrite = T)
  
})
```


