---
title: "Integration of donor only and with lab"
date: "2024-01-05"
author: "Jesse Rop"
output:
  html_document:
    toc: true
    theme: united
    code_folding: hide
    df_print: paged
---

```{r}
suppressPackageStartupMessages({
  library(Seurat)
  # library(sctransform)
  # library(rgl)
  library(ggrepel)
  # library(ggpubr)
  library(dplyr) 
  library(stringr)
  library(purrr)
  library(readr)
  library(tibble)
  library(ggplot2)
  # library(ggnewscale)
  library(tidyr)
  library(cowplot)
  # library(scDblFinder)
  library(SeuratData)
  library(SeuratDisk)
  # library(scmap)
  library(SingleCellExperiment)
  library(pheatmap)
  library(plotly)
  # library(Hmisc)
  # library(rmarkdown)
  library(RColorBrewer)
  # library(MAST)
  library(ggvenn)
  # library("biomaRt")
  library(conflicted)
  # library(SoupX)
  library(MetBrewer)
  # library(dreamlet)
  # library(muscat)
  # library(ExperimentHub)
  # library(zenith)
  library(scater)
  library(slingshot)
  library(harmony)
  library(ggforce)
  # library(miloR)
  library(scater)
  library(scran)
  library(patchwork)
  # library(scRNAseq)
  library(scuttle)
  library(irlba)
  library(BiocParallel)
  library(tradeSeq)
  library(ComplexHeatmap)
  library(circlize)
  library(readxl)
  library(ggh4x)
  conflict_prefer("select", "dplyr")
  conflict_prefer("filter", "dplyr")
  conflict_prefer("rename", "dplyr")
  conflicts_prefer(dplyr::count)
  conflicts_prefer(base::as.data.frame)
  
})
```


```{r setup}
sample_set = "Mali2"

# knitr::opts_knit$set(root.dir = paste0("/Users/jr35/Google Drive/My Drive/PHD_documents/malaria_phd/", sample_set))
knitr::opts_knit$set(root.dir = paste0("/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/", sample_set))
```

```{r}
published_dset_dir <- "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/published_dsets/"

read_dir_scvi2seu <- "data/processed/Pf/m2_all/scvi2seu/"
read_dir_stage_DE_markers <- "data/processed/Pf/m2_all/stage_DE_markers/"
read_dir_integrated_scvi_cleanup <- "data/processed/Pf/m2_all/integrated_scvi_cleanup/"

save_dir_integrated_scvi_cleanup <- "data/processed/Pf/m2_all/integrated_scvi_cleanup/"


```

#  integration of all MSC

### Common functions

#### Source commong functions, varriables and tables
```{r}
##Boxplot labeling function
source("../multipurpose_scripts_lnk/seurat_sce/seu_sce_common_fns.R")
source("../multipurpose_scripts_lnk/plotting_common_fns.R")
source("/nfs/users/nfs_j/jr35/Mali2/mali22_code/pf_common_vars.R")
```



#####!!! Run DE below to find markers to help in doublet detection. Not sure which one to go with


```{r, message=FALSE, warning=FALSE}
# Generated in 'all_integrated_scvi_object_cleanup_2remove_misplaced_clusters.Rmd' 
# all_jcC_seu_scvi_noM55 <- readRDS("data/processed/Pf/m2_all/scvi2seu/all_jcC_seu_scvino_M55.RDS")
# all_jcC_seu_scvi_noM55 <- readRDS(paste0(read_dir_scvi2seu, 'all_jcC_seu_scvino_M55.RDS'))

```

```{r, eval=T}
## Read the scvi integrated object with misplaced clusters of less than 1% in asexual, male and female stages removed
all_jcC_scvi_noM55_no_cluster_misplaced_cells <- readRDS(paste0(read_dir_integrated_scvi_cleanup, 'all_jcC_seu_scvi_stg_noM55_afm_cln_no_cluster_misplaced_cells.RDS'))

```

```{r}
# stg_names = c('Female', 'Male', 'Asexual')

```


```{r}
all_jcC_seu_scvi_stg_noM55_afm <- SplitObject(all_jcC_scvi_noM55_no_cluster_misplaced_cells, split.by= "stage_afm")
```


```{r}
all_jcC_seu_scvi_stg_noM55_afm <- c(list(all_jcC_scvi_noM55_no_cluster_misplaced_cells) %>% set_names("all"), 
                                    all_jcC_seu_scvi_stg_noM55_afm)
```


```{r}
map(all_jcC_seu_scvi_stg_noM55_afm, ~.x@meta.data %>% count(stage_afm, leiden) %>% arrange(desc(n)))
```

```{r}
map(all_jcC_seu_scvi_stg_noM55_afm, ~.x@meta.data %>% count(leiden) %>% arrange(desc(n)))

```

```{r}
clusters2keep4DE <- map(all_jcC_seu_scvi_stg_noM55_afm, ~.x@meta.data %>% count(leiden) %>% arrange(desc(n)) %>% filter(n>150) %>% pull(leiden))
clusters2keep4DE
```

```{r}
clusters2remove4DE <- map(all_jcC_seu_scvi_stg_noM55_afm, ~.x@meta.data %>% count(leiden) %>% arrange(desc(n)) %>% filter(n<=150) %>% pull(leiden))
clusters2remove4DE
```

```{r, fig.height=6, fig.width=10}
## Highlight likely misplaced clusters to remove
map2(all_jcC_seu_scvi_stg_noM55_afm, clusters2keep4DE, possibly(~DimPlot(.x, reduction = "scvi_umap", pt.size = 0.01, cells.highlight = colnames(.x[,!.x$leiden %in% .y]))))
```

```{r}
all_jcC_seu_scvi_stg_noM55_afm <- map2(all_jcC_seu_scvi_stg_noM55_afm, clusters2keep4DE, ~subset(.x, subset = leiden %in% .y))
```

```{r}
map(all_jcC_seu_scvi_stg_noM55_afm, ~.x@meta.data %>% count(leiden) %>% arrange(desc(n)))
```

```{r}
DimPlot(all_jcC_scvi_noM55_no_cluster_misplaced_cells, group.by = "leiden", reduction = "scvi_umap", label = T)

```

```{r}
map(all_jcC_seu_scvi_stg_noM55_afm, ~.x@meta.data %>% count(stage_afm, leiden, orig.ident) %>% group_by(leiden) %>% arrange(desc(n), .by_group = T) %>% filter(n>50))

```

```{r}
all_jcC_seu_scvi_stg_noM55_afm <- map(all_jcC_seu_scvi_stg_noM55_afm, ~SetIdent(.x, value = "leiden"))

```


```{r, eval=T}
wilcox_scviLeiden_markers_4DbtDetection <- map(all_jcC_seu_scvi_stg_noM55_afm, ~FindAllMarkers(.x ))
```


```{r, warning=FALSE, message=FALSE, eval=T}
wilcox_scviLeiden_markers_4DbtDetection_anot <- map(wilcox_scviLeiden_markers_4DbtDetection, ~.x %>%  left_join(., Pf3D7_genes_plasmoDB[,c("gene_id", "Gene")], by = c("gene" = "gene_id")))

# wilcox_scviLeiden_markers_4DbtDetection_anot
```


```{r, eval=T}
saveRDS(wilcox_scviLeiden_markers_4DbtDetection_anot, paste0(save_dir_integrated_scvi_cleanup, 'wilcox_scviLeiden_markers_4DbtDetection_anot.RDS'))

```

```{r, eval=T}
## Read in DE results to avoid recalculating
wilcox_scviLeiden_markers_4DbtDetection_anot <- readRDS(paste0(save_dir_integrated_scvi_cleanup, 'wilcox_scviLeiden_markers_4DbtDetection_anot.RDS'))

```


```{r}
map(all_jcC_seu_scvi_stg_noM55_afm, ~FeaturePlot(.x, features = "nFeature_RNA", reduction = "scvi_umap", label = T))
map(all_jcC_seu_scvi_stg_noM55_afm, ~DimPlot(.x, group.by = "leiden", reduction = "scvi_umap", label = T))

```


```{r}
DimPlot(all_jcC_scvi_noM55_no_cluster_misplaced_cells, group.by = "leiden", reduction = "scvi_umap", label = T)

```

```{r, warning=FALSE, message=FALSE}
map(wilcox_scviLeiden_markers_4DbtDetection_anot, ~.x %>% 
      # filter(gene %in% gns) %>% 
      arrange(desc(avg_log2FC)) %>% 
      filter(p_val_adj< 0.05 & avg_log2FC>0) %>%
      group_by(cluster) %>% 
      slice_min(order_by = p_val_adj, n = 30) %>% 
      slice_max(order_by = avg_log2FC, n = 30))
```


```{r, warning=FALSE, message=FALSE}
top_de_tbl <- map(wilcox_scviLeiden_markers_4DbtDetection_anot, ~.x %>% 
                    # filter(gene %in% gns) %>% 
                    arrange(desc(avg_log2FC)) %>% 
                    filter(p_val_adj< 0.05 & avg_log2FC>0) %>%
                    group_by(cluster) %>% 
                    slice_min(order_by = p_val_adj, n = 40) %>% 
                    slice_max(order_by = avg_log2FC, n = 20) %>%
                    ungroup() %>%
                    mutate(across(cluster, ~droplevels(factor(.x, paste(1:50))))) %>%
                    arrange(cluster) %>%
                    mutate(across(cluster, as.character))
)

top_de_tbl
```

```{r}
DimPlot(all_jcC_scvi_noM55_no_cluster_misplaced_cells, group.by = "leiden", reduction = "scvi_umap", label = T)

```


```{r}
top_de_tbl[[1]] %>% filter(cluster %in% c("15")) %>% 
  pull(Gene) %>% str_replace(., "-", "_") %>% dput()
```

```{r, warning=FALSE, message=FALSE}
asx_markers_for_gam_dblt <- c("PF3D7-0831700", "PF3D7-0501300", "PF3D7-0202000", "PF3D7-0113000", "PF3D7-1372200", "PF3D7-1401400", "PF3D7-1001500")
```


```{r, fig.width=7.5, fig.height=2}
asx_markers_for_gam_dblt_exp <- FetchData(object = all_jcC_seu_scvi_stg_noM55_afm[[1]], vars = asx_markers_for_gam_dblt, slot = "counts") 

```



```{r, fig.width=7.5, fig.height=2}
tbl_umap_gn <- all_jcC_seu_scvi_stg_noM55_afm[[1]]@reductions$scvi_umap@cell.embeddings %>% as.data.frame() %>% rownames_to_column("bcode") %>% left_join(., all_jcC_seu_scvi_stg_noM55_afm[[1]]@meta.data %>% rownames_to_column("bcode")) %>%  left_join(., asx_markers_for_gam_dblt_exp %>% rownames_to_column("bcode"))

```


```{r, fig.width=7.5, fig.height=2}
tbl_umap_gn <- tbl_umap_gn %>%
  mutate(mean_asx_gns = rowMeans(across(starts_with("PF3D7")), na.rm = TRUE),
         sum_asx_gns = rowSums(across(starts_with("PF3D7")), na.rm = TRUE))


```

```{r}
tbl_umap_gn_asx <- tbl_umap_gn %>%
  mutate(# fem_asx_dblt_mean = case_when(mean_asx_gns >= 2 & (leiden == "8") ~ "yes", 
    #                               mean_asx_gns < 2 & (leiden == "8") ~ "no"),
    # fem_asx_dblt_sum = case_when(sum_asx_gns >= 3 & (leiden == "8") ~ "yes", 
    #                               sum_asx_gns < 3 & (leiden == "8") ~ "no"), 
    fem_asx_dblt_mean = case_when(mean_asx_gns >= 2 & (leiden == "8" | str_detect(stage_fld, "emale")) ~ "yes", 
                                  mean_asx_gns < 2 & (leiden == "8" | str_detect(stage_fld, "emale")) ~ "no"),
    fem_asx_dblt_sum = case_when(sum_asx_gns >= 3 & (leiden == "8" | str_detect(stage_fld, "emale")) ~ "yes", 
                                 sum_asx_gns < 3 & (leiden == "8" | str_detect(stage_fld, "emale")) ~ "no"))
# fem_asx_dblt_mean = ifelse(mean_asx_gns > 2 & (leiden == "8" | str_detect(stage_fld, "ale")), "yes", "no"),
# fem_asx_dblt_sum = ifelse(sum_asx_gns > 3 & (leiden == "8" | str_detect(stage_fld, "ale")), "yes", "no")) 


# tbl_umap_gn_asx %>%
#   arrange(fem_asx_dblt_mean_allgams) %>%
#   ggplot(aes(x = umap_1, y = umap_2, colour = fem_asx_dblt_mean_allgams)) +
#   geom_point(size = 0.0001) 


tbl_umap_gn_asx %>%
  arrange(fem_asx_dblt_mean) %>%
  ggplot(aes(x = umap_1, y = umap_2, colour = fem_asx_dblt_mean)) +
  geom_point(size = 0.0001) 


```

```{r}
tbl_umap_gn_asx %>% arrange(fem_asx_dblt_sum) %>%
  ggplot(aes(x = umap_1, y = umap_2, colour = fem_asx_dblt_sum)) +
  geom_point(size = 0.0001) 


```


```{r}
tbl_umap_gn_asx %>% arrange(fem_asx_dblt_sum) %>%
  ggplot(aes(x = umap_1, y = umap_2, colour = fem_asx_dblt_sum)) +
  geom_point(size = 0.0001) +
  facet_wrap(fem_asx_dblt_sum ~.)


```

```{r}
tbl_umap_gn_asx %>%  #filter(leiden == "8") %>%
  ggplot(aes(x = fem_asx_dblt_mean, y = mean_asx_gns)) + geom_boxplot() +
  geom_text(
    data = ~ dplyr::count(.x, fem_asx_dblt_mean),
    aes(fem_asx_dblt_mean, Inf, label = paste0("n=", n)),
    vjust = 1.2
  )

tbl_umap_gn_asx %>%  #filter(leiden == "8") %>%
  ggplot(aes(x = fem_asx_dblt_sum, y = sum_asx_gns)) + geom_boxplot() +
  geom_text(
    data = ~ dplyr::count(.x, fem_asx_dblt_sum),
    aes(fem_asx_dblt_sum, Inf, label = paste0("n=", n)),
    vjust = 1.2
  )



```



```{r}
tbl_umap_gn_asx %>%  #filter(leiden == "8") %>%
  ggplot(aes(x = fem_asx_dblt_sum, y = sum_asx_gns)) + geom_sina(size = 0.0001) +
  geom_text(
    data = ~ dplyr::count(.x, fem_asx_dblt_sum),
    aes(fem_asx_dblt_sum, Inf, label = paste0("n=", n)),
    vjust = 1.2
  )



```


```{r}
tbl_umap_gn_asx_hires_stages <- tbl_umap_gn_asx %>%
  mutate(stage_scvi_hires_fem = case_when( fem_asx_dblt_sum == "yes" & leiden == "8" ~ "fem8_asx_dblt",
                                           fem_asx_dblt_sum == "yes" & leiden != "8" ~ "fem_non8_asx_dblt",
                                           fem_asx_dblt_sum == "no" & leiden == "8" ~ "fem8_activated_like",
                                           leiden == "9" ~ "fem9_low2",
                                           leiden == "10" ~ "fem10_low2",
                                           leiden == "14" ~ "fem14",
                                           leiden == "15" ~ "fem15_egress",
                                           T ~ stage_asx_c))



```

```{r}
tbl_umap_gn_asx_hires_stages%>% count(fem_asx_dblt_sum, stage_asx_c, stage_scvi_hires_fem)



```


Add the metadata for the activated_fem plus asexual stages to the main scvi object
```{r}
all_jcC_seu_scvi_stg_noM55_afm_ActivAsexDbts <- map(all_jcC_seu_scvi_stg_noM55_afm, ~AddMetaData(
  .x, tbl_umap_gn_asx_hires_stages %>% select(bcode, stage_scvi_hires_fem) %>% column_to_rownames("bcode")
))

```

```{r}
# save the overal object with activated+asex doublet annotation
saveRDS(all_jcC_seu_scvi_stg_noM55_afm_ActivAsexDbts, paste0(save_dir_integrated_scvi_cleanup, "all_jcC_seu_scvi_stg_noM55_afm_ActivAsexDbts.RDS"))
saveRDS(all_jcC_seu_scvi_stg_noM55_afm_ActivAsexDbts[[1]], paste0(save_dir_integrated_scvi_cleanup, "all_jcC_seu_scvi_stg_noM55_ActivAsexDbts.RDS"))

```

```{r}
saveRDS(tbl_umap_gn_asx_hires_stages, paste0(save_dir_integrated_scvi_cleanup, "tbl_umap_gn_asx_hires_stages.RDS"))

```


Remove the doublets composing activated_fem plus asexual stages and save
```{r}
all_jcC_seu_scvi_noM55_afm_cln <- map(all_jcC_seu_scvi_stg_noM55_afm_ActivAsexDbts, ~subset(.x, subset = stage_scvi_hires_fem %in% c("fem8_asx_dblt", "fem_non8_asx_dblt"), invert = T ))

```

```{r}
# save the overal object with activated+asex doublet annotation
saveRDS(all_jcC_seu_scvi_noM55_afm_cln, paste0(save_dir_integrated_scvi_cleanup, "all_jcC_seu_scvi_noM55_afm_cln.RDS"))

```

