---
title: "MSC QC and preprocessing"
date: '2022-07-11'
author: 'Jesse Rop'
output:
  html_document:
    toc: true
    theme: united
    code_folding: hide
    df_print: paged
---

```{r}
suppressPackageStartupMessages({
  library(Seurat)
  library(sctransform)
  # library(rgl)
  library(patchwork)
  # library(DoubletFinder)
  library(ggrepel)
  library(ggpubr)
  library(dplyr) 
  library(stringr)
  library(purrr)
  library(readr)
  library(tibble)
  library(ggplot2)
  library(tidyr)
  library(cowplot)
  # library(scDblFinder)
  library(SeuratData)
  library(SeuratDisk)
  library(plotly)
  library(Hmisc)
  library(rmarkdown)
  library(RColorBrewer)
  # library(Platypus)
  library(ggvenn)
  library(conflicted)
  # library(SoupX)
  library(MetBrewer)
  library(ggh4x)
  library(SingleCellExperiment)
  # library(scmap)
  # library(ggsankey)
  # library(findPC)
  library(BPCells)
  # library(furrr)
  # library(future.batchtools)
  library(parallel)
  library(EnhancedVolcano)
  library(DropletUtils)
  library(ggforce)
  library(scran)
  library(SingleR)
  library(scDblFinder)
  
  conflict_prefer("select", "dplyr")
  conflict_prefer("filter", "dplyr")
  conflict_prefer("rename", "dplyr")
  conflict_prefer("map", "purrr")
  conflict_prefer("count", "dplyr")
  conflicts_prefer(base::saveRDS)
  conflicts_prefer(SingleCellExperiment::colData)
  conflicts_prefer(base::as.data.frame)
  conflicts_prefer(base::intersect)
  conflicts_prefer(dplyr::desc)
  conflicts_prefer(dplyr::count)
})
```



# MSC Preprocessing

## setup, read input files and exploratory visualizations and general functions

```{r, setup}
knitr::opts_knit$set(root.dir = '/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/Mali2')

```

### Common functions

#### Source commong functions, varriables and tables
```{r}
##Boxplot labeling function
source("/nfs/users/nfs_j/jr35/multipurpose_scripts/seurat_sce/seu_sce_common_fns.R")
source("/nfs/users/nfs_j/jr35/Mali2/mali22_code/project_plotting_fns.R")
source("/nfs/users/nfs_j/jr35/Mali2/mali22_code/pf_common_vars.R")

```

#### Run emptydrops on all 
```{r}
## NOTE - USE raw_feature_bc_matrix.h5 and not the folder raw_feature_bc_matrix/ since nextflow can't expand to all the donor paths when using the folder after specifying 5736STDY*
##!!! NOTE The hdf5 matrix makes the running of emptydrops very slow so need to convert to dgCMatrix - https://github.com/MarioniLab/DropletUtils/issues/55

## Run emptydrops on all 
# nextflow run ../mali22_code_lnk/nf_scripts/edrops.nf --scrpt "/nfs/users/nfs_j/jr35/multipurpose_scripts/seurat_sce/edrops.R" --input_raw_mtx "/lustre/scratch126/tol/teams/lawniczak/projects/malaria_single_cell/mali_field_runs/2022/data/cellranger_runs/Pf/5736STDY*/outs/raw_feature_bc_matrix.h5" --o_path "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/Mali2/data/processed/Pf/" --retain_nm "wo_retain,w_retain" --retain_val "Inf,NULL" --limt "20,50,100,150,200" --fdr_l "0.01" -resume


```

###################START- RAW READING#############

```{r, eval=T}
pf_solo_mixed_mdata_decode <- read_csv("data/raw/pf_solo_mixed_mdata_decode.csv")
```

## Genotype clustering for MSC

initialize variable for the sample names

```{r}
# # select sample names
# # slct_sample_names <-c("MSC48", "MSC68", "MSC14", "MSC49", "MSC60", "MSC66", "MSC67", "MSC70", "MSC24", "MSC33", "MSC40", "MSC54", "MSC55") %>% str_sort(., numeric = T)
# 
# slct_sample_names <- pf_solo_mixed_mdata_decode$sample_nm
# ## get relevant sample names
# pf_solo_mixed_mdata_decode_slct <- pf_solo_mixed_mdata_decode %>% filter(sample_nm %in% slct_sample_names)
# 
# ##Sample ID
# sample_name <- str_sort(pf_solo_mixed_mdata_decode_slct$sample_nm)
# smpl_nms <-str_sort(pf_solo_mixed_mdata_decode_slct$sample_nm)
# 
# ##Sample IDs
# source_irods <- pf_solo_mixed_mdata_decode_slct[,c('sample_nm', 'irods_id')] %>% deframe() %>%.[sample_name]

```


```{r}

slct_sample_names <- pf_solo_mixed_mdata_decode$sample_nm
# slct_sample_names <-c("MSC68", "MSC14", "MSC49", "MSC55") %>% str_sort(., numeric = T)


# ## poor quality samples
sample_rm <- c("MSC1", "MSC24", "MSC37", "MSC38", "MSC39")
sample_mxd <- pf_solo_mixed_mdata_decode %>% filter(mixed_infection2 == "mixed") %>% pull(sample_nm)
# 
# # slct_sample_names[-c(sample_rm)]
slct_sample_names <- slct_sample_names[!(slct_sample_names %in% c(sample_rm, sample_mxd))]

## get relevant sample names
pf_solo_mixed_mdata_decode_slct <- pf_solo_mixed_mdata_decode %>% filter(sample_nm %in% slct_sample_names)

##Sample ID
sample_name <- str_sort(pf_solo_mixed_mdata_decode_slct$sample_nm)
smpl_nms <-str_sort(pf_solo_mixed_mdata_decode_slct$sample_nm)

##Sample IDs
source_irods <- pf_solo_mixed_mdata_decode_slct[,c('sample_nm', 'irods_id')] %>% deframe() %>%.[sample_name]

```


```{r}
# ## limit for different donors
# edrops_thresh <- rep(50, length(pf_solo_mixed_mdata_decode$sample_nm)) %>% set_names(pf_solo_mixed_mdata_decode$sample_nm)
# edrops_thresh[["MSC1"]] <- 150
# edrops_thresh[["MSC13"]] <- 100
# edrops_thresh[["MSC14"]] <- 100
# edrops_thresh[["MSC24"]] <- 200
# edrops_thresh[["MSC37"]] <- 200
# edrops_thresh[["MSC38"]] <- 200
# edrops_thresh[["MSC53"]] <- 150
# edrops_thresh[["MSC57"]] <- 150
# edrops_thresh[["MSC50_SLO"]] <- 100
```


```{r}
## read manual thresholds
edrops_thresh <- readRDS("data/processed/Pf/m2_all/man_thresh.RDS")
```




```{r, fig.width=15, fig.height=5}
donor_10x_mdata_sk21_summ <- readRDS("data/processed/Pf/m2_all/donor_10x_mdata_sk21_summ.RDS") %>%
  filter(donor %in% slct_sample_names) 

```


```{r, fig.width=15, fig.height=5}

donor_10x_mdata_sk21_summ %>% count(frac_load, overload, frac_over, targeted_cells)
```



```{r, message=F, warning=F, eval=T}
##Read BPcells matrices
all_cbender_mdata <- list.files("data/processed/Pf", pattern = "cb_mdata.csv$", full.names = T, recursive = T, include.dirs = T) %>% 
  set_names(nm = (str_remove_all(.,'data/processed/Pf/|/cbender/cb_mdata.*'))) %>% 
  .[sample_name] %>%
  .[!is.na(.)] %>%
  map(read_csv) 
```


```{r, message=F, warning=F, eval=T}
all_cbender_mdata
```


```{r, message=F, warning=F, eval=T}
imap(all_cbender_mdata, ~.x %>% 
      filter(cell_probability > 0.5) %>%
  ggplot(aes(x = background_fraction, y = cell_probability)) +
    geom_point(size = 0.1) +
    geom_vline(xintercept = 0.5) +
    labs(title = .y)
)
```


```{r, message=F, warning=F, eval=T, fig.height=9, fig.width=7}
all_cbender_mdata %>%
  bind_rows(., .id = "donor") %>% 
      filter(cell_probability > 0.8) %>%
  group_by(donor) %>% 
  mutate(bg_50 = sum(background_fraction > 0.5)) %>% 
  ungroup() %>%
  ggplot(aes(x = background_fraction)) +
    geom_histogram() +
    geom_text(aes(label=bg_50, x = 0.8, y = 200),  size = 3)+
    geom_vline(xintercept = 0.5) +
    facet_wrap(donor ~ ., scales = "free_y", ncol = 5)

```

```{r, message=F, warning=F, eval=T, fig.height=8, fig.width=12}
all_cbender_mdata %>%
  bind_rows(., .id = "donor") %>% 
      filter(cell_probability > 0.8) %>%
  count(donor, background_fraction>0.5)

```

```{r, message=F, warning=F, eval=T}
imap(all_cbender_mdata, ~.x %>% 
      filter(cell_probability > 0.5) %>%
  ggplot(aes(x = background_fraction, y = cell_size)) +
    geom_point(size = 0.1) +
    geom_vline(xintercept = 0.5) +
    labs(title = .y)
)
```

```{r, message=F, warning=F, eval=T}
imap(all_cbender_mdata, ~.x %>% 
      filter(cell_probability > 0.5) %>%
  ggplot(aes(x = cell_probability, y = cell_size)) +
    geom_point(size = 0.1) +
    geom_vline(xintercept = 0.9) +
    labs(title = .y)
)
```

```{r, message=F, warning=F, eval=T}
##Read BPcells matrices
all_cbender_mdata_pass.5 <- map(all_cbender_mdata, ~.x %>% filter(cell_probability>0.5) %>% pull(barcode))

```

```{r, message=F, warning=F, eval=T}
##Read BPcells matrices
all_cbender_mdata_pass.9 <- map(all_cbender_mdata, ~.x %>% filter(cell_probability>0.9) %>% pull(barcode))

```

## Save data
```{r}
part <- "Part1"
outdir <- paste0("/lustre/scratch126/tol/teams/lawniczak/users/jr35/sk_25_QC/PmML03_PowML03_QC_objects/", part, "/")

# processed_data_noretain <- readRDS(paste0(outdir, "Part1_EmptyDrops_pmpo_samples_50_to_500_wo_retain.RDS"))
```


```{r}
# processed_data_noretain_50 <- map(processed_data_noretain, ~.x[["50"]] %>% filter(!is.na(Barcode) )) %>% .[sample_name]
```


```{r}
processed_data_w_retain <- readRDS("data/processed/Pf/m2_all/processed_data_w_retain.RDS")
processed_data_wo_retain <- readRDS("data/processed/Pf/m2_all/processed_data_wo_retain.RDS")
```

```{r, fig.height=4.0, fig.width=4.0}
# M48, M49, M60
map(slct_sample_names, ~{
  print(paste0(.x, "_"))
  lst <- processed_data_wo_retain[str_detect(names(processed_data_wo_retain), paste0(.x, "_"))]
  lst <- lst[!str_detect(names(lst), "_20_")]
  names(lst) <- str_remove_all(names(lst), "MSC[0-9]+_|_retain")
  print(names(lst))
  lst <- map(lst, ~.x$Barcode)
  ggvenn(lst,
       show_percentage = F,
       text_size = 4,
       set_name_size = 4) +
    labs(title = .x)
})

```

```{r, fig.height=4.0, fig.width=4.0}
# M48, M49, M60
map(names(edrops_thresh[edrops_thresh >50]), ~{
  print(paste0(.x, "_"))
  lst <- processed_data_wo_retain[str_detect(names(processed_data_wo_retain), paste0(.x, "_"))]
  lst <- lst[!str_detect(names(lst), "_20_")]
  names(lst) <- str_remove_all(names(lst), "MSC[0-9]+_|_retain")
  print(names(lst))
  lst <- map(lst, ~.x$Barcode)
  ggvenn(lst,
       show_percentage = F,
       text_size = 4,
       set_name_size = 4) +
    labs(title = .x)
})

```


```{r}
names(processed_data_w_retain )
```


```{r}
wo_rtn_50 <- paste0(names(edrops_thresh), "_", edrops_thresh, "_wo_retain")
w_rtn_50 <- paste0(names(edrops_thresh), "_", edrops_thresh, "_w_retain")

wo_rtn_100 <- paste0(names(edrops_thresh), "_", "100", "_wo_retain")
w_rtn_100 <- paste0(names(edrops_thresh), "_", "100", "_w_retain")
```


```{r}
processed_data_noretain_50 <- processed_data_wo_retain[wo_rtn_50] %>% set_names(names(edrops_thresh)) %>% .[sample_name]
processed_data_withretain_50 <- processed_data_w_retain[w_rtn_50] %>% set_names(names(edrops_thresh))%>% .[sample_name]

processed_data_noretain_100 <- processed_data_wo_retain[wo_rtn_100] %>% set_names(names(edrops_thresh))%>% .[sample_name]
processed_data_withretain_100 <-  processed_data_w_retain[w_rtn_100] %>% set_names(names(edrops_thresh))%>% .[sample_name]

```


```{r}
saveRDS(processed_data_noretain_50, "data/processed/Pf/m2_all/processed_data_noretain_50.RDS")
```


```{r}
overlap_tbl <- pmap(list(processed_data_noretain_50, processed_data_withretain_50, processed_data_noretain_100, processed_data_withretain_100), ~{
  data.frame(
  "Limit (no retain): 50" = length(..1$Barcode),
  "Limit (retain): 50" = length(..2$Barcode),
  "Overlap 50 (prop)" = length(intersect(..1$Barcode, ..2$Barcode))/ length(unique(c(..1$Barcode, ..2$Barcode))),
  "Limit (no retain): 100" = length(..3$Barcode),
  "Limit (retain): 100" = length(..4$Barcode),
  "Overlap 100 (prop)" = length(intersect(..3$Barcode, ..4$Barcode))/ length(unique(c(..3$Barcode, ..4$Barcode))),
  "Overlap 50.100 noRet (prop)" = length(intersect(..1$Barcode, ..3$Barcode))/ length(unique(c(..1$Barcode, ..3$Barcode))),
  "Overlap all (prop)" = length(Reduce(intersect, list(..1$Barcode, ..2$Barcode, ..3$Barcode, ..4$Barcode)))/ length(unique(c(..1$Barcode, ..2$Barcode, ..3$Barcode, ..4$Barcode))),
  check.names = F
)
  }) %>%
  bind_rows(.id = "donor")

overlap_tbl
```

```{r}

overlap_tbl
```


```{r}
# nms_cb <- names(all_cbender_mdata)

overlap_tbl_cbender <- pmap(list(processed_data_noretain_50, processed_data_noretain_100, all_cbender_mdata_pass.5, all_cbender_mdata_pass.9), ~{
# overlap_tbl_cbender <- pmap(list(processed_data_noretain_50, processed_data_noretain_100, all_cbender_mdata_pass.9, all_cbender_mdata_pass.5), ~{
  data.frame(
  "Limit (no retain): 50" = length(..1$Barcode),
  "Limit (no retain): 100" = length(..2$Barcode),
  "CBendr" = length(..3),
  "CBendr.9" = length(..4),
  "Overlap 50:CBendr (prop)" = length(intersect(..1$Barcode, ..3))/ length(unique(c(..1$Barcode, ..3))),
  "Overlap 100:CBendr (prop)" = length(intersect(..2$Barcode, ..3))/ length(unique(c(..2$Barcode, ..3))),
  "50 in CBendr" = sum(..1$Barcode %in% ..3),
  "Overlap all (prop)" = length(Reduce(intersect, list(..1$Barcode, ..2$Barcode, ..3)))/ length(unique(c(..1$Barcode, ..2$Barcode, ..3))),
  check.names = F
)
  }) %>%
  bind_rows(.id = "donor")

overlap_tbl_cbender

```



```{r, fig.width=10, fig.height=5}
## Function to make line plots to compare the different cell calling methods and the overlap between them

methds_ln_plt_nohline <- function(tbl, x_var = "donor", y_var, col_var = "mthds_union") {
  ggplot(data = tbl, aes(x= !!rlang::sym(x_var), y = !!rlang::sym(y_var), colour = !!rlang::sym(col_var)))  +
  geom_point(size = 4) +
  geom_line(aes(group = !!rlang::sym(col_var)), size = 1) +
  theme_classic() + 
  theme(text = element_text(size =20),
        axis.text.x = element_text(size =20, angle = 45, hjust = 1),
        legend.position = "bottom")
}

```

```{r, fig.width=14, fig.height=5}
overlap_tbl_cbender %>% 
  pivot_longer(cols = c("Limit (no retain): 50", "Limit (no retain): 100", "CBendr", "CBendr.9", "50 in CBendr"), names_to = "Cell_id_mthd", values_to = "Cells") %>%
  mutate(across(donor, ~str_remove(., "_[0-9].*")),
         Cells_log10 = log10(Cells)) %>%
  methds_ln_plt_nohline(., x_var = "donor", y_var = "Cells_log10", col_var = "Cell_id_mthd")

```



```{r, fig.width=14, fig.height=4.3}
overlap_tbl_cbender %>% 
  pivot_longer(cols = c("Limit (no retain): 50", "Limit (no retain): 100", "CBendr", "CBendr.9", "50 in CBendr"), names_to = "Cell_id_mthd", values_to = "Cells") %>%
  mutate(across(donor, ~str_remove(., "_[0-9].*"))) %>%
  methds_ln_plt_nohline(., x_var = "donor", y_var = "Cells", col_var = "Cell_id_mthd")

```


```{r, fig.width=10, fig.height=5}
## Function to make line plots to compare the different cell calling methods and the overlap between them

methds_ln_plt <- function(tbl, x_var = "donor", y_var, col_var = "mthds_union") {
  ggplot(data = tbl, aes(x= !!rlang::sym(x_var), y = !!rlang::sym(y_var), colour = !!rlang::sym(col_var)))  +
  geom_point(size = 3) +
  geom_line(aes(group = !!rlang::sym(col_var)), size = 1) +
  geom_hline(yintercept = .50) +
  geom_hline(yintercept = .70) +
  theme_classic() + 
  theme(text = element_text(size =20),
        axis.text.x = element_text(size =20, angle = 45, hjust = 1),
        legend.position = "bottom")
}

```

```{r, fig.width=10, fig.height=4.3}
overlap_tbl_cbender %>% 
  pivot_longer(cols = c("Overlap 50:CBendr (prop)", "Overlap 100:CBendr (prop)"), names_to = "Cell_id_mthd", values_to = "Cells") %>%
  mutate(across(donor, ~str_remove(., "_[0-9].*")))  %>%
  methds_ln_plt(., x_var = "donor", y_var = "Cells", col_var = "Cell_id_mthd")

```

```{r, fig.width=10, fig.height=4.3}
overlap_tbl_cbender %>% 
  pivot_longer(cols = c("Overlap 50:CBendr (prop)", "Overlap 100:CBendr (prop)"), names_to = "Cell_id_mthd", values_to = "Cells") %>%
  mutate(across(donor, ~str_remove(., "_[0-9].*")))  %>%
  methds_ln_plt(., x_var = "donor", y_var = "Cells", col_var = "Cell_id_mthd") + 
  scale_y_continuous(expand = c(0, 0.01), limits = c(0, 1))


```



```{r}
# overlap_tbl_cbender %>% 
#   pivot_longer(cols = -c(donor), names_pattern = "(.*)\\.(S.*)", names_to = c( "Dbt_method", ".value")) %>%
#   ggplot(aes(x= donor, y = Sensitivity, color = Dbt_method))  +
#   geom_point() +
#   geom_line(aes(group = Dbt_method), linetype = "dotted")+
#   geom_point(aes(y = Specificity)) +
#   geom_line(aes(y = Specificity, group = Dbt_method))+
#   scale_y_continuous( name = 'Sensitivity', sec.axis = sec_axis(~. *1,name = "Specificity"))

```

##### Loaded versus recovered cells

```{r, fig.width=15, fig.height=5}

mdata_10x_resc <- donor_10x_mdata_sk21_summ %>% left_join(overlap_tbl_cbender, by = "donor")
```

```{r, fig.width=14, fig.height=4.3}
map(c("overload", "frac_load", "p_map_cat", "peak"), ~{

  mdata_10x_resc %>% 
    pivot_longer(cols = c("Limit (no retain): 50", "Limit (no retain): 100", "CBendr", "CBendr.9", "50 in CBendr"), names_to = "Cell_id_mthd", values_to = "Cells") %>%
    mutate(across(donor, ~str_remove(., "_[0-9].*"))) %>%
    ggplot(aes(x= donor, y = Cells, color = Cell_id_mthd))  +
    geom_point(size = 4) +
    geom_line(aes(group = Cell_id_mthd), size = 1) +
    theme_classic()  +
    facet_grid(cols = vars(!!rlang::sym(.x)), scales = "free_x", space =  "free_x") + 
    theme(text = element_text(size =20),
          axis.text.x = element_text(size =20, angle = 45, hjust = 1),
          legend.position = "bottom")
})
```


```{r, fig.width=14, fig.height=4.3}
map(c("overload", "frac_load", "p_map_cat", "peak"), ~{

  mdata_10x_resc %>% 
  pivot_longer(cols = c("Overlap 50:CBendr (prop)", "Overlap 100:CBendr (prop)"), names_to = "Cell_id_mthd", values_to = "Cells") %>%
  mutate(across(donor, ~str_remove(., "_[0-9].*"))) %>%
  ggplot(aes(x= donor, y = Cells, color = Cell_id_mthd))  +
  geom_point(size = 4) +
  geom_line(aes(group = Cell_id_mthd), size = 1) +
  geom_hline(yintercept = .50) +
  geom_hline(yintercept = .70) +
  facet_grid(cols = vars(!!rlang::sym(.x)), scales = "free_x", space =  "free_x") +
  theme_classic() + 
  theme(text = element_text(size =20),
        axis.text.x = element_text(size =20, angle = 45, hjust = 1),
        legend.position = "bottom")
})
```



```{r, fig.width=15, fig.height=5}

mdata_10x_resc %>% 
  pivot_longer(cols = c("Limit (no retain): 50", "CBendr", "Limit (no retain): 100"), names_to = "Cell_id_mthd", values_to = "cellNo") %>%
  ggplot(aes(x =  log10(parasites_loaded), y =  log10(cellNo))) +
  geom_point(size = 4) +
  geom_line(aes(group = Cell_id_mthd), size = 1) +
  # scale_y_log10() +
  # scale_x_log10() +
  facet_wrap(Cell_id_mthd ~ .)
```

```{r, fig.width=15, fig.height=5}

mdata_10x_resc %>% 
  pivot_longer(cols = c("Limit (no retain): 50", "CBendr", "Limit (no retain): 100"), names_to = "Cell_id_mthd", values_to = "cellNo") %>%
  ggplot(aes(x = log10(rbcs_in_mix), y = log10(cellNo))) +
  geom_point(size = 4) +
  geom_line(aes(group = Cell_id_mthd), size = 1) +
  facet_wrap(Cell_id_mthd ~ .)
```


```{r, fig.width=15, fig.height=5}

donor_10x_mdata_sk21_summ %>% count(frac_load, overload, frac_over, targeted_cells)
```


```{r, fig.width=9, fig.height=4}

mdata_10x_resc_cell_mthd <- mdata_10x_resc %>% 
  pivot_longer(cols = c("Limit (no retain): 50", "CBendr", "Limit (no retain): 100"), names_to = "Cell_id_mthd", values_to = "cellNo") 

```

```{r, fig.width=9, fig.height=4}
map(c("overload", "frac_load", "p_map_cat", "peak"), ~{

  mdata_10x_resc_cell_mthd%>%
  ggplot(aes(y =  cellNo, x = !!rlang::sym(.x) )) +
  geom_boxplot() +
  geom_point(size = 1) +
  facet_wrap(Cell_id_mthd ~ .)+ 
  theme(text = element_text(size =20),
        axis.text.x = element_text(angle = 25, hjust = 1))
})
```



```{r, fig.width=9, fig.height=4}

mdata_10x_resc_cell_mthd %>%
  ggplot(aes(y =  cellNo, x = frac_load )) +
  geom_boxplot() +
  geom_point(size = 1) +
  geom_text_repel(data = mdata_10x_resc_cell_mthd %>% filter(cellNo > 20000), aes(label = donor), vjust = -0.5, color = "red", size = 5) +
  facet_wrap(Cell_id_mthd ~ .)+ 
  theme(text = element_text(size =20),
        axis.text.x = element_text(angle = 25, hjust = 1))


```


```{r, fig.width=9, fig.height=4}

mdata_10x_resc_cell_mthd %>%
  ggplot(aes(y =  cellNo, x = frac_load )) +
  geom_boxplot() +
  geom_point(size = 1) +
  geom_text_repel(data = mdata_10x_resc_cell_mthd %>% filter(overload == "Yes_20k"), aes(label = donor), vjust = -0.5, color = "red", size = 5) +
  facet_wrap(Cell_id_mthd ~ .)+ 
  theme(text = element_text(size =20),
        axis.text.x = element_text(angle = 25, hjust = 1))


```

```{r, eval=FALSE}
cell_count_table <- readRDS(paste0(outdir, "Part1_EmptyDrops_pmpo_samples_50_to_500_w_wo_retain_cell_count_table.RDS"))
cell_count_table
```
