---
title: "Integration of donor only and with lab"
date: "2024-01-05"
author: "Jesse Rop"
output:
  html_document:
    toc: true
    theme: united
    code_folding: hide
    df_print: paged
---

```{r}
suppressPackageStartupMessages({
  library(Seurat)
  library(sctransform)
  # library(rgl)
  # library(patchwork)
  library(ggrepel)
  # library(ggpubr)
  library(dplyr) 
  library(stringr)
  library(purrr)
  library(readr)
  library(tibble)
  library(ggplot2)
  # library(ggnewscale)
  library(tidyr)
  library(cowplot)
  # library(scDblFinder)
  library(SeuratData)
  library(SeuratDisk)
  # library(scmap)
  # library(SingleCellExperiment)
  library(pheatmap)
  library(plotly)
  # library(Hmisc)
  # library(rmarkdown)
  library(RColorBrewer)
  # library(MAST)
  library(ggvenn)
  # library("biomaRt")
  library(conflicted)
  # library(SoupX)
  library(MetBrewer)
  library(knitr)
  # library(readxl)
  # library(SCpubr)
  # library(ggh4x)
  # library(htmlwidgets)
  library(slingshot)
  library(harmony)
  library(ggforce)
  conflict_prefer("select", "dplyr")
  conflict_prefer("filter", "dplyr")
  conflict_prefer("rename", "dplyr")
  conflicts_prefer(dplyr::count)
  conflicts_prefer(base::as.data.frame)
  
})
```


#  integration of all MSC

### Common functions

#### Source commong functions, varriables and tables
```{r}
##Boxplot labeling function
source("/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/multipurpose_scripts/seurat_sce/seu_sce_common_fns.R")
source("/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/multipurpose_scripts/plotting_common_fns.R")
source("/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/Mali2/mali22_code/pf_common_vars.R")
```

```{r setup}
sample_set = "Mali2"

optimum_k_qcd <- c("MSC33" =8, "MSC48" =4, "MSC49" =6, "MSC55" =7, "MSC60" =7, "MSC66" =8, "MSC38" =4, "MSC40" =8, "MSC50_MACS" =1, "MSC53" =1, "MSC57" =1, "MSC24" =1, "MSC37" =5, "MSC39" =4, "MSC45" =1, "MSC50_SLO" =1, "MSC54" =1, "MSC67" =1, "MSC68" =3, "MSC70" =1)

optimum_k_qcd <- optimum_k_qcd[sort(names(optimum_k_qcd))]

# knitr::opts_knit$set(root.dir = paste0("/Users/jr35/Google Drive/My Drive/PHD_documents/malaria_phd/", sample_set))
knitr::opts_knit$set(root.dir = paste0("/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/", sample_set))
```

```{r}
msc_w_cln_strns_raw <- readRDS("data/processed/Pf/m2_all/msc_w_cln_strns_raw.RDS")

```

```{r}
## Subset asexuals and remove donors with no asexuals
msc_w_cln_strns_raw_asex <- compact(map(msc_w_cln_strns_raw, possibly(~.x[,.x@meta.data$stage_c == "Asexual"])))

## Remove donors with less than 100 asexual parasites
msc_w_cln_strns_raw_asex <- msc_w_cln_strns_raw_asex[unlist(map(msc_w_cln_strns_raw_asex, ~dim(.x)[2] > 100))]

# Remove objects/samples without cells since this leads to an error when running normalization before integration - solution from https://github.com/satijalab/seurat/issues/8347
# layersList <- lapply(m2_asex_list@assays$RNA@layers,function(x){dim(x)})

```

```{r}
## Making list of objects and renaming before integrating
m2_asex_list <- merge(x = msc_w_cln_strns_raw_asex[[1]], y = msc_w_cln_strns_raw_asex[2:length(msc_w_cln_strns_raw_asex)], add.cell.ids = str_remove(names(msc_w_cln_strns_raw_asex), "SC"))
```


Write out annotated MCA reference in .h5ad 
```{r, message=FALSE, warning=FALSE, eval=T}
##Change factor metadata to character as these are not handled properly when converting to h5ad
m2_asex_list_raw <- m2_asex_list
m2_asex_list_raw@meta.data <- m2_asex_list_raw@meta.data %>% mutate(across(where(is.factor), as.character))

## !!!NB - NEEDS SORTING IN FUTURE UPGRADING TO SEURAT 5 RESULTED IN ERROR AS DESCRIBED https://github.com/mojaveazure/seurat-disk/issues/147#top
m2_asex_list_raw[["RNA3"]] <- as(object = m2_asex_list_raw[["RNA"]], Class = "Assay")
DefaultAssay(m2_asex_list_raw) <- "RNA3"
m2_asex_list_raw[["RNA"]] <- NULL
m2_asex_list_raw <- RenameAssays(object = m2_asex_list_raw, RNA3 = 'RNA')

# SaveH5Seurat(m2_asex_list_raw, filename =  paste0("/Users/jr35/Google Drive/My Drive/PHD_documents/malaria_phd/",sample_set,"/data/processed/Pf/m2_asex_list_raw.h5Seurat"), overwrite = T)
SaveH5Seurat(m2_asex_list_raw, filename =  paste0("data/processed/Pf/m2_all/m2_asex_list_raw.h5Seurat"), overwrite = T)

# Convert(paste0("/Users/jr35/Google Drive/My Drive/PHD_documents/malaria_phd/",sample_set,"/data/processed/Pf/m2_asex_list_raw.h5Seurat"), dest = "h5ad", overwrite = T)
Convert(paste0("data/processed/Pf/m2_all/m2_asex_list_raw.h5Seurat"), dest = "h5ad", overwrite = T)

```

```{r, message=FALSE, warning=FALSE}
## save for running stdseurat in farm
saveRDS(m2_asex_list, "data/processed/Pf/m2_all/m2_asex_list.RDS")

```

```{r, eval=T}
gogo()
## Run SNORM on farm like below
## !!NB - reducing the number of hypervariable genes results in scattered and disjointed clusters. higher hvg number better

# nextflow run submsn_seu_norm.nf --scrpt "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/multipurpose_scripts/seurat_sce/seu_stdnorm.R" --input_seu "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/Mali2/data/processed/Pf/m2_all/m2_asex_list.RDS" --o_file_name "m2_asex_seu_norm.RDS" --umap_name "UMAP_" --hvg 300 --cluster_resoln 0.1 --cl_nm "seurat_clusters_nm" --umap_redctn_nm "umap.unintegrated" --redctn "pca" --integrtd_pc30 "no" --elbo_nm "m2_asex_seu_norm_elbo.RDS" --resume
```


```{r, eval=T}
gogo()
## Run harmony integration with the number of PCs being automatically detected by findPC

# nextflow run submsn_intgrtn_pc.nf --scrpt "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/multipurpose_scripts/seurat_sce/seu_integrtn_pc_auto.R" --input_seu "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/Mali2/data/processed/Pf/m2_all/m2_asex_seu_norm.RDS" --mthd "HarmonyIntegration" --o_file_name "m2_asex_harmony_int.RDS" --cluster_resoln 1 --cl_nm "harmony_clusters" --umap_redctn_nm "umap.harmony" --new_redctn "integrated.harmony" --intgrtn_pc 30 --integrtd_pc_man "no" --elbo_nm "m2_asex_harmony_int_elbo.RDS"  --findpc_mthd "perpendicular line" --resume

#"perpendicular line" is 6. kmeans which is 5 was giving very good umap
```


```{r}
m2_asex_harmony_int <-  readRDS("data/processed/Pf/m2_all/m2_asex_harmony_int.RDS")
m2_asex_harmony_int_elbo <-  readRDS("data/processed/Pf/m2_all/m2_asex_harmony_int_elbo.RDS")
m2_asex_harmony_int_elbo
```

```{r}
DimPlot(m2_asex_harmony_int, group.by = "StagePrelim", pt.size = 0.4, reduction = "umap.harmony")
```

```{r}
DimPlot(m2_asex_harmony_int, dims = c(1,3), group.by = "donor", pt.size = 0.8, reduction = "umap.harmony")
DimPlot(m2_asex_harmony_int, dims = c(2,3), group.by = "donor", pt.size = 0.4, reduction = "umap.harmony")
```


```{r, fig.width=12, fig.height=4}
FeaturePlot(m2_asex_harmony_int, features = c("PF3D7-0301800", "PF3D7-1002000", "PF3D7-0608800"), pt.size = 0.01, reduction = "umap.harmony", ncol = 3, slot = "data")
```

HRP2-PF3D7_0831800
EXP1-PF3D7_1121600
FIRA-PF3D7_0501400
LDH-PF3D7_1324900
SERA5-PF3D7_0207600
KAHRP-PF3D7_0202000
CRT-PF3D7_0709000
MRP1-PF3D7_0112200
MPC1- PF3D7_1340800
```{r, fig.width=12, fig.height=12}

FeaturePlot(m2_asex_harmony_int, features = c("PF3D7-0831800", "PF3D7-1121600", "PF3D7-0501400","PF3D7-1324900","PF3D7-0207600", "PF3D7-0202000","PF3D7-0709000","PF3D7-0112200","PF3D7-1340800"), pt.size = 0.01, reduction = "umap.harmony", ncol = 3, slot = "data")
```

```{r}
DimPlot(m2_asex_harmony_int, reduction = "pca", group.by = "stage", pt.size = 1.5)
```


```{r, warning=FALSE, message=FALSE, eval=FALSE}
# Display the combined datasets as an interactive 3D plot 
plot_ly(data = data.frame(m2_asex_harmony_int@reductions[["umap.harmony"]]@cell.embeddings), x = ~umapharmony_1, y = ~umapharmony_2, z = ~umapharmony_3,  color= m2_asex_harmony_int@meta.data$stage, opacity = 0.8, size = 1,   type = 'scatter3d')

```





```{r}
DimPlot(m2_asex_harmony_int, pt.size = 0.4, reduction = "umap.harmony", group.by = "harmony_clusters")
```


```{r}
## 
m2_asex_harmony_int <- FindClusters(m2_asex_harmony_int, resolution = 0.26, cluster.name = "harmony_clusters_ss")

```

```{r}
DimPlot(m2_asex_harmony_int, pt.size = 0.4, reduction = "umap.harmony", group.by = "harmony_clusters_ss")
```


```{r}
Idents(m2_asex_harmony_int) <- "harmony_clusters_ss"
```


```{r}
m2_asex_harmony_int_jnd <- JoinLayers(m2_asex_harmony_int)
asx_devt_mrks <- FindAllMarkers(m2_asex_harmony_int_jnd)
```


```{r}
top3_gns <- asx_devt_mrks %>% group_by(cluster) %>% arrange(p_val_adj, desc(avg_log2FC)) %>% slice_head(n = 3) %>% left_join(., Pf3D7_genes_plasmoDB[, c("gene_id", "Gene")], by = c("gene" = "gene_id"))
top3_gns
```


```{r, fig.width=12, fig.height=12}
top3_gns$Gene
# acs7 - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10151525/, https://journals.asm.org/doi/10.1128/spectrum.05014-22 https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.3000271
# lsa3 - https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5380959/
# PF3D7-0918100 - https://hal.inrae.fr/hal-03752215/file/2022_Swale_Sci-Transl-Med_MAA.pdf
# PF3D7-1477500 - exported- https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8365696/
# PF3D7-0532600 - exported-  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9320996/
# PF3D7-0114500 hyp10 - exported, clonaly variant -  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC8406225/
# PfD80 - https://www.biorxiv.org/content/10.1101/2024.03.19.585770v1.full

  
```


```{r}
top3_fc_gns <- asx_devt_mrks %>% group_by(cluster) %>% arrange(desc(avg_log2FC)) %>% slice_head(n = 3) %>% left_join(., Pf3D7_genes_plasmoDB[, c("gene_id", "Gene")], by = c("gene" = "gene_id"))
top3_fc_gns
```


```{r, fig.width=12, fig.height=12}

FeaturePlot(m2_asex_harmony_int, features = top3_gns$gene, pt.size = 0.01, reduction = "umap.harmony", ncol = 3, slot = "data")
```

```{r, eval=T}
Seurat_object <- JoinLayers(m2_asex_harmony_int)

## Convert seurat object to SCE
sce_obj <- SingleCellExperiment(assays = list(counts = as(Seurat_object[["RNA"]]$counts, Class = "dgCMatrix")), colData = Seurat_object@meta.data)
    
# print(sce_obj)
logcounts(sce_obj) <- log2((counts(sce_obj) + 1))
normcounts(sce_obj) <- as(Seurat_object[["RNA"]]$data, Class = "dgCMatrix")
rowData(sce_obj)$feature_symbol <- str_replace(rownames(sce_obj), "-", "_")
reducedDims(sce_obj) <- SimpleList(PCA = Seurat_object@reductions[["pca"]]@cell.embeddings, UMAP = Seurat_object@reductions[["umap.harmony"]]@cell.embeddings)


# print(sce_obj)
print(colnames(colData(sce_obj)))

## Convert seurat object to SCE
sce_obj <- slingshot(sce_obj, 
            clusterLabels = "harmony_clusters_ss", 
            reducedDim = "PCA", 
            start.clus = 1,
            # end.clus = E_CLSTR,
            shrink =1, 
            stretch = 1,
            allow.break = F)


```

```{r}
m2_asex_harmony_sce_ss <- sce_obj
##Prepare slingshot dataset (SDS) object 
m2_asex_harmony_sce_ss_sds <- SlingshotDataSet(sce_obj)

plot(reducedDims(m2_asex_harmony_sce_ss)$UMAP[,1:2], col = brewer.pal(9,"Set1")[as.factor(m2_asex_harmony_sce_ss$stage)], pch=16, asp = 0.7)
lines(m2_asex_harmony_sce_ss_sds, lwd=2, col="black",dims = 1:2)
```


```{r, results="asis"}

umap_meta_df <- reducedDims(m2_asex_harmony_sce_ss)$UMAP[,c(1,2,3)] %>% as.data.frame() %>%rownames_to_column("cell_bc") %>% left_join(., m2_asex_harmony_sce_ss@colData[,c("stage", "slingPseudotime_1", "orig.ident")] %>% as.data.frame() %>% rownames_to_column("cell_bc"), by = "cell_bc")  #%>% 
# mutate(across(strain_dset, ~factor(., levels = rev(strain_dset_lvls_don)))) %>% arrange(strain_dset

# umap_meta_df <- reducedDims(m2_asex_harmony_sce_ss)$UMAP[,c(1,2,3)] %>% as.data.frame() %>%rownames_to_column("cell_bc") %>% left_join(., m2_asex_harmony_sce_ss@colData[,c("stage", "slingPseudotime_1", "slingPseudotime_2", "orig.ident")] %>% as.data.frame() %>% rownames_to_column("cell_bc"), by = "cell_bc")  #%>% 
# # mutate(across(strain_dset, ~factor(., levels = rev(strain_dset_lvls_don)))) %>% arrange(strain_dset


tm <- theme_classic()+
  theme(axis.text=element_blank(), 
        axis.title=element_blank(),
        legend.text = element_text(size = 22) ,
        legend.title = element_text(size = 24, face = "bold") )

umap_meta_df %>% 
  ggplot(aes(x = umapharmony_1, y =umapharmony_2, color = slingPseudotime_1)) + geom_point(size=0.5) + 
  scale_color_distiller(name="Pseudotime", direction = 1, palette = "Blues") + 
  tm

umap_meta_df %>% 
  ggplot(aes(x = umapharmony_2, y =umapharmony_3, color = slingPseudotime_1)) + geom_point(size=0.5) + 
  scale_color_distiller(name="Pseudotime", direction = 1, palette = "Blues") + 
  tm


```

```{r, eval=T}
gogo()
## Run SNORM on farm like below
# nextflow run submsn_intgrtn.nf --scrpt "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/multipurpose_scripts/seurat_sce/seu_integrtn_rpca.R" --input_seu "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/Mali2/data/processed/Pf/m2_all/m2_asex_seu_norm.RDS" --mthd "RPCAIntegration" --o_file_name "m2_asex_rpca_int.RDS" --cluster_resoln 1 --cl_nm "rpca_clusters" --umap_redctn_nm "umap.rpca" --new_redctn "integrated.rpca" --resume
```


```{r, eval=T}
gogo()
## Run SNORM on farm like below
# nextflow run submsn_intgrtn_rpca.nf --scrpt "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/multipurpose_scripts/seurat_sce/seu_integrtn_rpca.R" --input_seu "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/Mali2/data/processed/Pf/m2_all/m2_asex_seu_norm.RDS" --mthd "RPCAIntegration" --o_file_name "m2_asex_rpca_int.RDS" --cluster_resoln 1 --cl_nm "rpca_clusters" --umap_redctn_nm "umap.rpca" --new_redctn "integrated.rpca" --k_wt 70 --norm_mthd "LogNormalize" --resume
```

```{r}
m2_asex_rpca_int <-  readRDS("data/processed/Pf/m2_all/m2_asex_rpca_int.RDS")
```


```{r}
DimPlot(m2_asex_rpca_int, group.by = "StagePrelim", pt.size = 0.4, reduction = "umap.rpca")
DimPlot(m2_asex_rpca_int, dims = c(2,3), group.by = "StagePrelim", pt.size = 0.4, reduction = "umap.rpca")
```

```{r, eval=FALSE}
DimPlot(m2_asex_rpca_int, dims = c(1,3), group.by = "donor", pt.size = 0.4, reduction = "umap.rpca")
DimPlot(m2_asex_rpca_int, dims = c(2,3), group.by = "donor", pt.size = 0.4, reduction = "umap.rpca")
```

```{r, warning=FALSE, message=FALSE, eval=FALSE}
# Display the combined datasets as an interactive 3D plot 
plot_ly(data = data.frame(m2_asex_rpca_int@reductions[["umap.rpca"]]@cell.embeddings), x = ~umaprpca_1, y = ~umaprpca_2, z = ~umaprpca_3,  color= m2_asex_rpca_int@meta.data$stage, opacity = 0.8, size = 1,   type = 'scatter3d')

```

```{r}
DimPlot(m2_asex_harmony_int, reduction = "pca", group.by = "StagePrelim")
```


```{r, eval=T}
gogo()
## Run SNORM on farm like below
## !!NB - reducing the number of hypervariable genes results in scattered and disjointed clusters. higher hvg number better

# nextflow run submsn_seu_norm.nf --scrpt "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/multipurpose_scripts/seurat_sce/seu_sctnorm.R" --input_seu "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/Mali2/data/processed/Pf/m2_all/m2_asex_list.RDS" --o_file_name "m2_asex_seu_sct.RDS" --umap_name "UMAP_" --hvg 250 --cluster_resoln 0.1 --cl_nm "seurat_clusters_nm" --umap_redctn_nm "umap.unintegrated" --redctn "pca" --integrtd_pc30 "yes" --elbo_nm "m2_asex_seu_sct_elbo.RDS" --resume
```


```{r, eval=T}
gogo()
## Run SNORM on farm like below
# nextflow run submsn_intgrtn_rpca.nf --scrpt "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/multipurpose_scripts/seurat_sce/seu_integrtn_rpca.R" --input_seu "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/Mali2/data/processed/Pf/m2_all/m2_asex_seu_sct.RDS" --mthd "RPCAIntegration" --o_file_name "m2_asex_sct_rpca_int.RDS" --cluster_resoln 1 --cl_nm "rpca_clusters" --umap_redctn_nm "umap.rpca" --new_redctn "integrated.rpca" --intgrtn_pc 6 --k_wt 70 --norm_mthd "SCT" --resume
```

```{r}
m2_asex_sct_rpca_int <-  readRDS("data/processed/Pf/m2_all/m2_asex_sct_rpca_int.RDS")
```


```{r, fig.width=14, fig.height=5}
DimPlot(m2_asex_sct_rpca_int, pt.size = 0.4, reduction = "umap.rpca", group.by = c("rpca_clusters", "StagePrelim"), dims = c(2,3))
```

## Re-intergrate only the asexuals and reumap

```{r, warning=FALSE, message=FALSE, eval=FALSE}
Convert("data/processed/Pf/m2_all/m2_asex_list_scvi.h5ad", dest = "h5seurat", overwrite = TRUE)
m2_asex_list_scvi <- LoadH5Seurat("data/processed/Pf/m2_all/m2_asex_list_scvi.h5seurat", assays = "RNA")
m2_asex_list_scvi

```

```{r, warning=FALSE, message=FALSE, eval=FALSE}
DimPlot(m2_asex_list_scvi)
```



```{r}
##Read MCA V3 blood stage reference dataset
# EF_V3_ref <- readRDS("../sc_velo/data/raw/RoadtoUMAP/pseudotime/raw_combined_cut_0.4.RDS")
EF_V3_ref <- readRDS("../Mali/data/raw/mca_v3_ref/raw_combined_cut_0.4_nodoublets_stagenew.RDS")

# create seurat from raw counts
EF_V3_ref_asx_cnts <- CreateSeuratObject(counts = EF_V3_ref[, EF_V3_ref@meta.data$stagenew == "asexuals"][["RNA"]]$counts, meta.data = EF_V3_ref[, EF_V3_ref@meta.data$stagenew == "asexuals"]@meta.data)

# EF_V3_ref_asx_cnts[["RNA5"]] <- as(object = EF_V3_ref_asx_cnts[["RNA"]], Class = "Assay5")
# DefaultAssay(EF_V3_ref_asx_cnts) <- "RNA5"
# EF_V3_ref_asx_cnts[["RNA"]] <- NULL
# EF_V3_ref_asx_cnts <- RenameAssays(object = EF_V3_ref_asx_cnts, RNA5 = 'RNA')

```

```{r}
## get asexuals subset
m2_list_asex <- map(msc_w_cln_strns_raw,  possibly(~.x[,.x@meta.data$stage_c == "Asexual"], NULL)) %>% compact()

## get samples with more than 100 ascuals
m2_list_asex <- m2_list_asex[unlist(map(m2_list_asex, ~dim(.x)[2] > 100))]

# m2_list_asex <- map(m2_list_asex, ~{
#   obj <- .x
#   obj@reductions$pca <- NULL
#   obj@reductions$umap <- NULL
#   return(obj)
#   
# })

```

```{r}
## Making list of objects and renaming before integrating
v3_m2_list_asex <- merge(x = EF_V3_ref_asx_cnts, y = m2_list_asex, add.cell.ids = c("Lab", str_remove(names(m2_list_asex), "SC")))
```


```{r, fig.width=12, fig.height=4}
# add stage metadata
v3_m2_list_asex <- v3_m2_list_asex@meta.data %>% 
  rownames_to_column('bcode') %>%
  mutate(dset_labmrg = if_else(str_detect(orig.ident, "MSC"),  str_remove(orig.ident, ".mrna"), "Lab"),
         StageFL = coalesce(stagenewx, stage),
         StageFL_ND = str_to_sentence(StageFL),
         dset = if_else(str_detect(orig.ident, "MSC"),  "Field", "Lab")
         ) %>%
  select(bcode, dset_labmrg, StageFL, StageFL_ND, dset) %>%
  column_to_rownames('bcode') %>% 
  AddMetaData(v3_m2_list_asex,.)


```

```{r, message=FALSE, warning=FALSE}
## save for running stdseurat in farm
saveRDS(v3_m2_list_asex, "data/processed/Pf/m2_all/v3_m2_list_asex.RDS")

```


Write out annotated asexual lab+field in .h5ad 
```{r, message=FALSE, warning=FALSE, eval=T}
##Change factor metadata to character as these are not handled properly when converting to h5ad
v3_m2_list_asex_raw <- v3_m2_list_asex
v3_m2_list_asex_raw@meta.data <- v3_m2_list_asex_raw@meta.data %>% mutate(across(where(is.factor), as.character))

## !!!NB - NEEDS SORTING IN FUTURE UPGRADING TO SEURAT 5 RESULTED IN ERROR AS DESCRIBED https://github.com/mojaveazure/seurat-disk/issues/147#top
v3_m2_list_asex_raw[["RNA3"]] <- as(object = v3_m2_list_asex_raw[["RNA"]], Class = "Assay")
DefaultAssay(v3_m2_list_asex_raw) <- "RNA3"
v3_m2_list_asex_raw[["RNA"]] <- NULL
v3_m2_list_asex_raw <- RenameAssays(object = v3_m2_list_asex_raw, RNA3 = 'RNA')

# SaveH5Seurat(v3_m2_list_asex_raw, filename =  paste0("/Users/jr35/Google Drive/My Drive/PHD_documents/malaria_phd/",sample_set,"/data/processed/Pf/v3_m2_list_asex_raw.h5Seurat"), overwrite = T)
SaveH5Seurat(v3_m2_list_asex_raw, filename =  paste0("data/processed/Pf/m2_all/v3_m2_list_asex_raw.h5Seurat"), overwrite = T)

# Convert(paste0("/Users/jr35/Google Drive/My Drive/PHD_documents/malaria_phd/",sample_set,"/data/processed/Pf/v3_m2_list_asex_raw.h5Seurat"), dest = "h5ad", overwrite = T)
Convert(paste0("data/processed/Pf/m2_all/v3_m2_list_asex_raw.h5Seurat"), dest = "h5ad", overwrite = T)

```

!!!NB - FARM CODE - DONT DELETE

```{r, eval=T}
gogo()
## Run SNORM on farm like below
## !!NB - reducing the number of hypervariable genes results in scattered and disjointed clusters. higher hvg number better

# nextflow run submsn_seu_norm.nf --scrpt "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/multipurpose_scripts/seurat_sce/seu_stdnorm.R" --input_seu "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/Mali2/data/processed/Pf/m2_all/v3_m2_list_asex.RDS" --o_file_name "v3_m2_asex_seu_norm.RDS" --umap_name "UMAP_" --hvg 300 --cluster_resoln 1 --cl_nm "seurat_clusters_nm" --umap_redctn_nm "umap.unintegrated" --redctn "pca" --integrtd_pc30 "no" --elbo_nm "v3_m2_asex_seu_norm_elbo.RDS" --resume
```


```{r}
v3_m2_asex_seu_norm <-  readRDS("data/processed/Pf/m2_all/v3_m2_asex_seu_norm.RDS")
```

```{r, fig.width=10, fig.height=5}
# visualize by batch and cell type annotation
# cell type annotations were previously added by Azimuth
DimPlot(v3_m2_asex_seu_norm, reduction = "umap.unintegrated", group.by = "StageFL_ND", label = F, dims = c(1,2), split.by = "dset") #+ scale_color_manual(values = sp_fld_colors)
```

```{r, fig.width=12, fig.height=4}
# visualize by batch and cell type annotation
# cell type annotations were previously added by Azimuth
DimPlot(v3_m2_asex_seu_norm, reduction = "umap.unintegrated", group.by = c("orig.ident", "StagePrelim"), label = F)
```


```{r, fig.width=12, fig.height=12}

FeaturePlot(v3_m2_asex_seu_norm, features = top3_gns$gene, pt.size = 0.01, reduction = "umap.unintegrated", ncol = 3, slot = "data")
```

!!!NB - FARM CODE - DONT DELETE
```{r, eval=T}
gogo()
## Run SNORM on farm like below
# nextflow run submsn_intgrtn.nf --scrpt "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/multipurpose_scripts/seurat_sce/seu_integrtn.R" --input_seu "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/Mali2/data/processed/Pf/m2_all/v3_m2_asex_seu_norm.RDS" --mthd "HarmonyIntegration" --o_file_name "v3_m2_asex_harmony.RDS" --cluster_resoln 1 --cl_nm "harmony_clusters_asex" --umap_redctn_nm "umap.harmony" --new_redctn "integrated.harmony" --resume
```


```{r, eval=T}
gogo()
## Run harmony integration with the number of PCs being automatically detected by findPC

# nextflow run submsn_intgrtn_pc.nf --scrpt "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/multipurpose_scripts/seurat_sce/seu_integrtn_pc_auto.R" --input_seu "/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/Mali2/data/processed/Pf/m2_all/v3_m2_asex_seu_norm.RDS" --mthd "HarmonyIntegration" --o_file_name "v3_m2_asex_harmony.RDS" --cluster_resoln 1 --cl_nm "harmony_clusters_asex" --umap_redctn_nm "umap.harmony" --new_redctn "integrated.harmony" --intgrtn_pc 30 --integrtd_pc_man "no" --elbo_nm "v3_m2_asex_harmony_elbo.RDS"  --findpc_mthd "perpendicular line" --resume
```


```{r}
v3_m2_asex_harmony <-  readRDS("data/processed/Pf/m2_all/v3_m2_asex_harmony.RDS")
v3_m2_asex_harmony_elbo <-  readRDS("data/processed/Pf/m2_all/v3_m2_asex_harmony_elbo.RDS")
```


```{r}
v3_m2_asex_harmony <- JoinLayers(v3_m2_asex_harmony)
```


```{r, fig.width=6, fig.height=5}
# visualize by batch and cell type annotation
# cell type annotations were previously added by Azimuth
DimPlot(v3_m2_asex_harmony, reduction = "umap.harmony", group.by = "StagePrelim", label = F, dims = c(1,2)) + scale_color_manual(values = sp_fld_colors)
```

```{r, fig.width=12, fig.height=4}
# visualize by batch and cell type annotation
# cell type annotations were previously added by Azimuth
DimPlot(v3_m2_asex_harmony, reduction = "umap.harmony", group.by = c("orig.ident", "stage"), label = F)
```


```{r, fig.width=6, fig.height=5}
# visualize by batch and cell type annotation
# cell type annotations were previously added by Azimuth
DimPlot(v3_m2_asex_harmony, reduction = "umap.harmony", group.by = "harmony_clusters_asex", label = T, dims = c(1,2))
```


```{r, fig.width=12, fig.height=12}

FeaturePlot(v3_m2_asex_harmony, features = top3_gns$gene, pt.size = 0.01, reduction = "umap.harmony", ncol = 3, slot = "data")
```

```{r, fig.width=12, fig.height=4}
# visualize by batch and cell type annotation
# cell type annotations were previously added by Azimuth
DimPlot(v3_m2_asex_harmony, reduction = "umap.harmony", group.by = c("StageFL"), label = F)
```

```{r, fig.width=12, fig.height=4}
# visualize by batch and cell type annotation
# cell type annotations were previously added by Azimuth
DimPlot(v3_m2_asex_harmony, reduction = "pca", group.by = c("StageFL"), label = F)
```

```{r, fig.width=12, fig.height=4}
# visualize by batch and cell type annotation
# cell type annotations were previously added by Azimuth
DimPlot(v3_m2_asex_harmony, reduction = "pca", group.by = c("dset"), label = F)
```

```{r, warning=FALSE, message=FALSE, eval=FALSE}
# Display the combined datasets as an interactive 3D plot

plot_ly(data = data.frame(v3_m2_asex_harmony@reductions[["pca"]]@cell.embeddings),
        x = ~PC_1, y = ~PC_2, z = ~PC_3,
        color= v3_m2_asex_harmony@meta.data$StageFL,
        # colors = c('blue', 'red'),
        opacity = 0.8,
        size = 0.2, 
        type = 'scatter3d'
)

```



```{r, warning=FALSE, message=FALSE, eval=FALSE}
# Display the combined datasets as an interactive 3D plot

plot_ly(data = data.frame(v3_m2_asex_harmony@reductions[["umap.harmony"]]@cell.embeddings),
        x = ~umapharmony_1, y = ~umapharmony_2, z = ~umapharmony_3,
        color= v3_m2_asex_harmony@meta.data$StageFL,
        # colors = c('blue', 'red'),
        opacity = 0.8,
        size = 0.2, 
        type = 'scatter3d'
)

```


```{r, warning=FALSE, message=FALSE, eval=FALSE}
# Display the combined datasets as an interactive 3D plot

plot_ly(data = data.frame(v3_m2_asex_harmony@reductions[["umap.harmony"]]@cell.embeddings),
        x = ~umapharmony_1, y = ~umapharmony_2, z = ~umapharmony_3,
        color= v3_m2_asex_harmony@meta.data$StageFL,
        # colors = c('blue', 'red'),
        opacity = 0.8,
        size = 0.2, 
        type = 'scatter3d'
)

```


```{r}
# strn_c_new_mdata_m22_min_qcd_mg <- strn_c_new_mdata_m22_min_qcd %>% 
#   bind_rows(., .id = "donor") %>% 
#   mutate(bcode = paste0(str_remove(donor, "SC"), "_", bcode), 
#          StrainDon = paste0(str_remove(donor, "SC"), "_", strain)) %>%
#   select(bcode, strain, StrainDon) %>% 
#   column_to_rownames("bcode") 
```

```{r, fig.width=12, fig.height=4}
# add stage metadata
# v3_m2_asex_harmony <- strn_c_new_mdata_m22_min_qcd_mg %>% select(StrainDon) %>%  AddMetaData(v3_m2_asex_harmony,.)

```

```{r, fig.width=12, fig.height=4}
# add stage metadata
# v3_m2_asex_harmony <- v3_m2_asex_harmony@meta.data %>% 
#   rownames_to_column('bcode') %>%
#   mutate(donor = str_remove(orig.ident, ".mrna"), 
#          # strain_don = case_when(str_detect(orig.ident, "MSC") ~ paste0(Strain_DN, "_", donor))
#          ) %>%
#   left_join(., irods_id_sk21_mdata_cln %>% select(sample_nm, Symptomatic, Hb_Type), by = c("donor" = "sample_nm")) %>%
#   select(bcode, donor, Symptomatic, Hb_Type) %>%
#   column_to_rownames('bcode') %>% 
#   AddMetaData(v3_m2_asex_harmony,.)

```

```{r, fig.width=15, fig.height=5}
# visualize by batch and cell type annotation
v3_m2_asex_harmony@meta.data %>% filter(str_detect(donor, "MSC")) %>% dplyr::count(donor, Symptomatic, Hb_Type)
```


```{r, fig.width=15, fig.height=5}
# visualize by batch and cell type annotation
m2_asex_harmony_tr <- v3_m2_asex_harmony[,v3_m2_asex_harmony@meta.data$dset == "Field"]
```
