---
title: "MSC QC and preprocessing"
date: '2022-07-11'
author: 'Jesse Rop'
output:
  html_document:
    toc: true
    theme: united
    code_folding: hide
    df_print: paged
---

```{r}
suppressPackageStartupMessages({
  library(Seurat)
  library(sctransform)
  # library(rgl)
  library(patchwork)
  # library(DoubletFinder)
  library(ggrepel)
  library(ggpubr)
  library(dplyr) 
  library(stringr)
  library(purrr)
  library(readr)
  library(tibble)
  library(ggplot2)
  library(tidyr)
  library(cowplot)
  # library(scDblFinder)
  library(SeuratData)
  library(SeuratDisk)
  library(plotly)
  library(Hmisc)
  library(rmarkdown)
  library(RColorBrewer)
  # library(Platypus)
  library(ggvenn)
  library(conflicted)
  # library(SoupX)
  library(MetBrewer)
  library(ggh4x)
  library(SingleCellExperiment)
  # library(scmap)
  # library(ggsankey)
  # library(findPC)
  library(BPCells)
  # library(furrr)
  # library(future.batchtools)
  library(parallel)
  library(EnhancedVolcano)
  library(DropletUtils)
  library(ggforce)
  library(slingshot)
  
  conflict_prefer("select", "dplyr")
  conflict_prefer("filter", "dplyr")
  conflict_prefer("rename", "dplyr")
  conflict_prefer("map", "purrr")
  conflict_prefer("count", "dplyr")
  conflicts_prefer(base::saveRDS)
  conflicts_prefer(SingleCellExperiment::colData)
  conflicts_prefer(base::as.data.frame)
})
```







# MSC Preprocessing


## setup, read input files and exploratory visualizations and general functions


```{r, setup}
# library(reticulate)
# # use_condaenv("/Users/jr35/envs/scv_jupcon/", required = TRUE)
# # matplotlib <- reticulate::import("matplotlib")
# # matplotlib$use("Agg", force = TRUE)
# 
# knitr::opts_knit$set(root.dir = '/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/Mali')
knitr::opts_knit$set(root.dir = '/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/Mali2')

```

### Common functions

#### Source commong functions, varriables and tables
```{r}
##Boxplot labeling function
source("/nfs/users/nfs_j/jr35/multipurpose_scripts/seurat_sce/seu_sce_common_fns.R")
source("/nfs/users/nfs_j/jr35/multipurpose_scripts/plotting_common_fns.R")
source("/nfs/users/nfs_j/jr35/Mali2/mali22_code/pf_common_vars.R")
```


######################## START integration including LassePortugal et al ########################
```{r}
##Read lasse et al harmony integration of atlas and natural infections
lasse_natural_infcns_seu_harmony <- readRDS("/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/lasse_natural_infcns_seu_harmony.RDS")

```

```{r}
## Convert from Seurat to SCE 
lasse_seu_harmony_dons <- lasse_natural_infcns_seu_harmony[, str_detect(lasse_natural_infcns_seu_harmony@meta.data$orig.ident, "endDry|MAL")]
lasse_seu_harmony_dons
```


```{r, warning=FALSE, message=FALSE}
v3_m2_asex_cr_filt_norm_harmony_jnd <- readRDS("data/processed/Pf/m2_all/v3_m2_asex_cr_filt_norm_harmony_jnd.RDS")
```

```{r}
v3_m2_asex_cr_filt_norm_harmony_jnd <- v3_m2_asex_cr_filt_norm_harmony_jnd
```

```{r}
v3_m2_asex_cr_filt_norm_harmony_jnd[["RNA"]]$counts <- as(v3_m2_asex_cr_filt_norm_harmony_jnd[["RNA"]]$counts, Class = "dgCMatrix")
v3_m2_asex_cr_filt_norm_harmony_jnd[["RNA"]]$data <- NULL
v3_m2_asex_cr_filt_norm_harmony_jnd[["RNA"]]$scale.data <- NULL
v3_m2_asex_cr_filt_norm_harmony_jnd[["SCT"]] <- NULL

```


```{r, warning=FALSE, message=FALSE}
v3_m2_asex_cr_filt_norm_harmony_jnd_list <- SplitObject(v3_m2_asex_cr_filt_norm_harmony_jnd, split.by = "orig.ident")
```


```{r}
lasse_seu_harmony_dons_jnd <- JoinLayers(lasse_seu_harmony_dons)

lasse_seu_harmony_dons_jnd[["RNA"]]$data <- NULL
lasse_seu_harmony_dons_jnd[["RNA"]]$scale.data <- NULL

lasse_seu_harmony_dons_jnd <- SplitObject(lasse_seu_harmony_dons_jnd, split.by = "orig.ident")

```

```{r, warning=FALSE, message=FALSE}
m2_lasse_asex <- c(v3_m2_asex_cr_filt_norm_harmony_jnd_list, lasse_seu_harmony_dons_jnd)
m2_lasse_asex <- merge(m2_lasse_asex[[1]], m2_lasse_asex[2:length(m2_lasse_asex)] )
m2_lasse_asex
```


```{r, warning=FALSE, message=FALSE}
saveRDS(m2_lasse_asex, "data/processed/Pf/m2_all/m2_lasse_asex.RDS")
```


```{r, eval=T}
gogo()
# bsub < /lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/Mali2/mali22_code_lnk/bash_scripts/submsn_seu_norm_integration_bsub.sh

```

```{r, eval=T}
# bsub < /lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/Mali2/mali22_code_lnk/bash_scripts/submsn_intgrtn_pc_harmony_bsub.sh

```


```{r, warning=FALSE, message=FALSE}
m2_lasse_asex_norm_harmony <- readRDS("data/processed/Pf/m2_all/m2_lasse_asex_norm_harmony.RDS")
# m2_lasse_asex_norm_harmony_pc <- readRDS("data/processed/Pf/m2_all/m2_lasse_asex_norm_harmony_pc.RDS")

```

```{r, warning=FALSE, message=FALSE}
m2_lasse_asex_norm_harmony_elbo <- readRDS("data/processed/Pf/m2_all/m2_lasse_asex_norm_harmony_elbo.RDS")
m2_lasse_asex_norm_harmony_elbo
```

```{r, warning=FALSE, message=FALSE}
DimPlot(m2_lasse_asex_norm_harmony, reduction = "umap.harmony", group.by = "harmony_clusters", order = T, pt.size = 0.01, label=T) 

```


```{r, warning=FALSE, message=FALSE}
DimPlot(m2_lasse_asex_norm_harmony_pc, reduction = "umap.harmony_pc", group.by = "harmony_pc_clusters", order = T, pt.size = 0.01, label=T) 
DimPlot(m2_lasse_asex_norm_harmony_pc, reduction = "umap.harmony_pc", group.by = "harmony_pc_clusters", order = T, pt.size = 0.01, label=T, dims = c(1,3)) 

```

```{r, warning=FALSE, message=FALSE, eval=T}
# Display the combined datasets as an interactive 3D plot

plot_ly(data = data.frame(m2_lasse_asex_norm_harmony_pc@reductions[["umap.harmony_pc"]]@cell.embeddings),
        x = ~umapharmonypc_1, y = ~umapharmonypc_2, z = ~umapharmonypc_3,
        color= m2_lasse_asex_norm_harmony_pc@meta.data$harmony_pc_clusters,
        # colors = c('blue', 'red'),
        opacity = 0.8,
        size = 1, 
        type = 'scatter3d'
)

```


```{r, warning=FALSE, message=FALSE}
DimPlot(m2_lasse_asex_norm_harmony, reduction = "umap.harmony", group.by = "orig.ident", order = T, pt.size = 0.01, label=T) 

```


```{r, warning=FALSE, message=FALSE}
m2_lasse_asex_norm_harmony <- m2_lasse_asex_norm_harmony@meta.data %>% 
  mutate(across(pseudotime.stages, ~str_replace_all(., c("Ring" = " ring", "Trophozoite" = " trophozoite", "DevelopingGametocyte" = "Gametocyte (developing)", "FemaleGametocyte" = "Female"))),
         stage = coalesce(sR_fine_stg, pseudotime.stages),
         group = case_when(str_detect(orig.ident, "MSC") ~ "MCA",
                           T ~ group)) %>%
  select(stage, group) %>%
  AddMetaData(m2_lasse_asex_norm_harmony, .)

```


```{r, warning=FALSE, message=FALSE, fig.width = 8, fig.height=3}
DimPlot(m2_lasse_asex_norm_harmony, reduction = "umap.harmony", split.by = "group", order = T, pt.size = 0.01, label=T) 

```


```{r, warning=FALSE, message=FALSE, fig.width = 10, fig.height=3.5}
# ap2-g pfs16 gexp02 gene_count
FeaturePlot(m2_lasse_asex_norm_harmony, reduction = "umap.harmony",  label = T, features = "PF3D7-1222600", order = T, split.by = "group")
FeaturePlot(m2_lasse_asex_norm_harmony, reduction = "umap.harmony",  label = T, features = "PF3D7-0406200", order = T, split.by = "group")
FeaturePlot(m2_lasse_asex_norm_harmony, reduction = "umap.harmony",  label = T, features = "PF3D7-1102500", order = T, split.by = "group")
FeaturePlot(m2_lasse_asex_norm_harmony, reduction = "umap.harmony",  label = T, features = "nFeature_RNA", order = T, split.by = "group")
FeaturePlot(m2_lasse_asex_norm_harmony, reduction = "umap.harmony",  label = T, features = "nCount_RNA", order = T, split.by = "group")


```

```{r, warning=FALSE, message=FALSE, fig.width = 10, fig.height=3.5}
# ap2-g pfs16 gexp02 gene_count
FeaturePlot(m2_lasse_asex_norm_harmony, reduction = "umap.harmony",  label = T, features = "PF3D7-1222600", order = T, split.by = "group", dims = c(1,3))
FeaturePlot(m2_lasse_asex_norm_harmony, reduction = "umap.harmony",  label = T, features = "PF3D7-0406200", order = T, split.by = "group", dims = c(1,3))
FeaturePlot(m2_lasse_asex_norm_harmony, reduction = "umap.harmony",  label = T, features = "PF3D7-1102500", order = T, split.by = "group", dims = c(1,3))
FeaturePlot(m2_lasse_asex_norm_harmony, reduction = "umap.harmony",  label = T, features = "nFeature_RNA", order = T, split.by = "group", dims = c(1,3))
FeaturePlot(m2_lasse_asex_norm_harmony, reduction = "umap.harmony",  label = T, features = "nCount_RNA", order = T, split.by = "group", dims = c(1,3))


```

```{r, warning=FALSE, message=FALSE, fig.width = 10, fig.height=3.5}
# gexp02 gene_count
FeaturePlot(m2_lasse_asex_norm_harmony, reduction = "integrated.harmony",  label = T, features = "PF3D7-1102500", order = T, split.by = "group", dims = c(2,4))

```

```{r, warning=FALSE, message=FALSE, eval=T}
# Display the combined datasets as an interactive 3D plot

plot_ly(data = data.frame(m2_lasse_asex_norm_harmony@reductions[["umap.harmony"]]@cell.embeddings),
        x = ~umapharmony_1, y = ~umapharmony_2, z = ~umapharmony_3,
        color= m2_lasse_asex_norm_harmony@meta.data$harmony_clusters,
        # colors = c('blue', 'red'),
        opacity = 0.8,
        size = 1, 
        type = 'scatter3d'
)

```


```{r, warning=FALSE, message=FALSE, eval=T}
# Display the combined datasets as an interactive 3D plot

plot_ly(data = data.frame(m2_lasse_asex_norm_harmony@reductions[["integrated.harmony"]]@cell.embeddings),
        x = ~harmony_2, y = ~harmony_3, z = ~harmony_4,
        color= m2_lasse_asex_norm_harmony@meta.data$stage,
        # colors = c('blue', 'red'),
        opacity = 0.8,
        size = 1, 
        type = 'scatter3d'
)

```

```{r, warning=FALSE, message=FALSE, eval=T}
# Display the combined datasets as an interactive 3D plot

m2_lasse_asex_norm_harmony_jnd <- JoinLayers(m2_lasse_asex_norm_harmony)

```


```{r, warning=FALSE, message=FALSE, eval=T}
# Display the combined datasets as an interactive 3D plot

plot_ly(data = data.frame(m2_lasse_asex_norm_harmony_jnd@reductions[["integrated.harmony"]]@cell.embeddings),
        x = ~harmony_2, y = ~harmony_3, z = ~harmony_4,
        color= m2_lasse_asex_norm_harmony_jnd["PF3D7-1102500",][["RNA"]]@layers$data,
        # colors = c('blue', 'red'),
        opacity = 0.8,
        size = 0.01, 
        type = 'scatter3d'
)

```


```{r, warning=FALSE, message=FALSE, eval=T}
# Display the combined datasets as an interactive 3D plot

# v3_m2_asex_cr_filt_norm_harmony_jnd_norm <- NormalizeData(v3_m2_asex_cr_filt_norm_harmony_jnd)

```

```{r, warning=FALSE, message=FALSE, eval=T}
# # Display the combined datasets as an interactive 3D plot
# 
# plot_ly(data = data.frame(v3_m2_asex_cr_filt_norm_harmony_jnd_norm@reductions[["integrated.harmony_pc_man"]]@cell.embeddings),
#         x = ~harmony_2, y = ~harmony_3, z = ~harmony_5,
#         color= v3_m2_asex_cr_filt_norm_harmony_jnd_norm["PF3D7-1102500",][["RNA"]]@layers$data,
#         # colors = c('blue', 'red'),
#         opacity = 0.8,
#         size = 0.01, 
#         type = 'scatter3d'
# )

```


######################## END integration including LassePortugal et al ########################


