---
title: "Integration of donor only and with lab"
date: "2024-01-05"
author: "Jesse Rop"
output:
  html_document:
    toc: true
    theme: united
    code_folding: hide
    df_print: paged
---

```{r}
suppressPackageStartupMessages({
  library(Seurat)
  # library(sctransform)
  # library(rgl)
  library(ggrepel)
  # library(ggpubr)
  library(dplyr) 
  library(stringr)
  library(purrr)
  library(readr)
  library(tibble)
  library(ggplot2)
  # library(ggnewscale)
  library(tidyr)
  library(cowplot)
  # library(scDblFinder)
  library(SeuratData)
  library(SeuratDisk)
  # library(scmap)
  library(SingleCellExperiment)
  library(pheatmap)
  library(plotly)
  # library(Hmisc)
  # library(rmarkdown)
  library(RColorBrewer)
  # library(MAST)
  library(ggvenn)
  # library("biomaRt")
  library(conflicted)
  # library(SoupX)
  library(MetBrewer)
  # library(dreamlet)
  # library(muscat)
  # library(ExperimentHub)
  # library(zenith)
  library(scater)
  library(slingshot)
  library(harmony)
  library(ggforce)
  # library(miloR)
  library(scater)
  library(scran)
  library(patchwork)
  # library(scRNAseq)
  library(scuttle)
  library(irlba)
  library(BiocParallel)
  library(tradeSeq)
  library(ComplexHeatmap)
  library(circlize)
  conflict_prefer("select", "dplyr")
  conflict_prefer("filter", "dplyr")
  conflict_prefer("rename", "dplyr")
  conflicts_prefer(dplyr::count)
  conflicts_prefer(base::as.data.frame)
  
})
```


```{r setup}
sample_set = "Mali2"

# knitr::opts_knit$set(root.dir = paste0("/Users/jr35/Google Drive/My Drive/PHD_documents/malaria_phd/", sample_set))
knitr::opts_knit$set(root.dir = paste0("/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/", sample_set))
```


#  integration of all MSC

### Common functions

#### Source commong functions, varriables and tables
```{r}
##Boxplot labeling function
source("../multipurpose_scripts_lnk/seurat_sce/seu_sce_common_fns.R")
source("../multipurpose_scripts_lnk/plotting_common_fns.R")
source("/nfs/users/nfs_j/jr35/Mali2/mali22_code/pf_common_vars.R")
```


```{r}
obj_names = c('M55', 'no_M55')

```

```{r}
scvi_de_markers <- read_csv("data/processed/Pf/m2_all/m2_all_scvi_marker_genes.csv")

```


```{r, warning=FALSE, message=FALSE}
 scvi_de_markers_anot <- scvi_de_markers %>% rename("gene" = `...1`) %>%  left_join(., Pf3D7_genes_plasmoDB[,c("gene_id", "Gene")], by = c("gene" = "gene_id"))

#  scvi_de_markers_anot
```

```{r, warning=FALSE, message=FALSE}
 scvi_de_markers_anot

```
```{r, warning=FALSE, message=FALSE}
scvi_de_markers_anot %>% filter(group1 == "Asexual" & `is_de_fdr_0.05` == T & non_zeros_proportion1 >0.75) %>% arrange(desc(lfc_median)) 


```

```{r, warning=FALSE, message=FALSE}
scvi_de_markers_anot %>% filter(group1 == "Schizont" & `is_de_fdr_0.05` == T) %>% arrange(desc(lfc_median)) 


```
```{r, warning=FALSE, message=FALSE}
scvi_de_markers_anot %>% filter(group1 == "Female" & `is_de_fdr_0.05` == T & non_zeros_proportion1 >0.85 & non_zeros_proportion2 <0.05) %>% arrange(desc(lfc_median)) 


```
```{r, warning=FALSE, message=FALSE}
scvi_de_markers_anot %>% filter(group1 == "Male" & `is_de_fdr_0.05` == T & non_zeros_proportion1 >0.85 & non_zeros_proportion2 <0.05) %>% arrange(desc(lfc_median)) 


```

```{r}
# saveRDS( scvi_de_markers_anot, "data/processed/Pf/m2_all/ scvi_de_markers_anot.RDS")
saveRDS( scvi_de_markers_anot, "data/processed/Pf/m2_all/scvi_de_markers_anot3.RDS")

```

```{r, warning=FALSE, message=FALSE}
scvi_de_markers_anot %>% 
  # filter(gene %in% gns) %>% 
  arrange(desc(avg_log2FC)) %>% 
    filter(p_val_adj< 0.05 & avg_log2FC>0) %>%
    group_by(cluster) %>% 
    slice_min(order_by = p_val_adj, n = 5) %>% 
    slice_max(order_by = avg_log2FC, n = 5)
```

```{r, warning=FALSE, message=FALSE}
map2( scvi_de_markers_anot[c("M55.Asexual", "no_M55.Asexual")], list(c("14","16", "17"), c("16","15", "10")), ~.x %>% 
  filter(cluster %in% .y) %>%
  arrange(desc(avg_log2FC)) %>% 
    filter(p_val_adj< 0.05 & avg_log2FC>0) %>%
    group_by(cluster) %>% 
    slice_min(order_by = p_val_adj, n = 30))
```


```{r, warning=FALSE, message=FALSE, fig.width=16, fig.height=6}
map(m2_all_raw_mrg_list_stg[c("M55.Asexual", "no_M55.Asexual")], ~FeaturePlot(.x, features = c("PF3D7-0829900", "PF3D7-1229200", "PF3D7-1222600", "PF3D7-1102500", "PF3D7-0818900"), order =T, ncol = 3))

```

cold-activated noncoding RNAs Temperature Regulated Untranslated Lncrna (tru-lncRNA) 
https://www.sciencedirect.com/science/article/pii/S0378111923003578 
https://www.nature.com/articles/s41564-021-00940-w
https://pmc.ncbi.nlm.nih.gov/articles/PMC12235521/
https://onlinelibrary.wiley.com/doi/10.1111/1744-7917.13383
```{r, warning=FALSE, message=FALSE}
cold_activated_RNAs <- c("PF3D7-1148100", "PF3D7-1148200", "PF3D7-1148500", "PF3D7-1370500", "PF3D-1370800", "PF3D7-1370900")
```


```{r, fig.width=14, fig.height=8}
map(m2_all_raw_mrg_list_stg[c("M55.Asexual", "no_M55.Asexual")], ~FeaturePlot(.x, features = cold_activated_RNAs, order =T, ncol = 3))
```