---
title: "m2_stg_markers"
date: "2025-03-31"
author: "Jesse Rop"
output:
  html_document:
    toc: true
    theme: united
    code_folding: hide
    df_print: paged
---


```{r}
suppressPackageStartupMessages({
  library(Seurat)
  library(sctransform)
  # library(rgl)
  # library(patchwork)
  library(ggrepel)
  # library(ggpubr)
  library(dplyr) 
  library(stringr)
  library(purrr)
  library(readr)
  library(tibble)
  library(ggplot2)
  # library(ggnewscale)
  library(tidyr)
  library(cowplot)
  # library(scDblFinder)
  library(SeuratData)
  library(SeuratDisk)
  # library(scmap)
  # library(SingleCellExperiment)
  library(pheatmap)
  library(plotly)
  # library(Hmisc)
  # library(rmarkdown)
  library(RColorBrewer)
  # library(MAST)
  library(ggvenn)
  # library("biomaRt")
  library(conflicted)
  # library(SoupX)
  library(MetBrewer)
  library(knitr)
  # library(readxl)
  # library(SCpubr)
  # library(ggh4x)
  # library(htmlwidgets)
  library(slingshot)
  library(harmony)
  library(ggforce)
  conflict_prefer("select", "dplyr")
  conflict_prefer("filter", "dplyr")
  conflict_prefer("rename", "dplyr")
  conflicts_prefer(dplyr::count)
  conflicts_prefer(base::as.data.frame)
  
})
```


#  integration of all MSC


```{r setup}
sample_set = "Mali2"

knitr::opts_knit$set(root.dir = paste0("/lustre/scratch126/tol/teams/lawniczak/users/jr35/phd/", sample_set))
```

### Common functions

#### Source commong functions, varriables and tables
```{r}
##Boxplot labeling function
source("../multipurpose_scripts_lnk/seurat_sce/seu_sce_common_fns.R")
source("../multipurpose_scripts_lnk/plotting_common_fns.R")
source("mali22_code_lnk/pf_common_vars.R")
```

```{r}
msc_w_cln_strns_mdata <- readRDS("data/processed/Pf/m2_all/msc_w_cln_strns_mdata.RDS")
```


```{r}
msc_w_cln_strns <- readRDS("data/processed/Pf/m2_all/msc_w_cln_strns.RDS")
```

```{r}

all_mrks <- readRDS("data/processed/Pf/m2_all/all_mrks.RDS")
```

```{r, fig.width=12, fig.height=4}
# add stage metadata
msc_w_cln_strns_raw <- readRDS("data/processed/Pf/m2_all/msc_w_cln_strns_raw.RDS")
```

```{r, fig.width=12, fig.height=4}
# add stage metadata
stg_mkrs <- readRDS("data/processed/Pf/m2_all/stg_mkrs.RDS")

```


```{r}
## Making list of objects and renaming before integrating
m2_seu <- merge(x = msc_w_cln_strns_raw[[1]], y = msc_w_cln_strns_raw[2:length(msc_w_cln_strns_raw)], add.cell.ids = str_remove(names(msc_w_cln_strns_raw), "SC"))
m2_seu$donor <- str_remove_all(m2_seu$orig.ident, "SC|\\.mrna")
m2_seu$stage_c <- factor(m2_seu$stage_c, levels = c("Asexual", "Female", "Female LE", "Male", "Male LE"))
```


```{r, fig.width=20, fig.height=5}
#ap2g, gdv1, pfs16, etramp10.3, gexp5, pfg14-744, pfg14-748
# m2_seu_jnd <- JoinLayers(m2_seu)
m2_seu_noM12 <- m2_seu[,m2_seu@meta.data$donor != "M12"]

```



!!!NOTE - RAW COUNTS BEING USED - NEED TO CHANGE TO NORMALISED(DATA) WHICH IS STANDARD
```{r, fig.width=20, fig.height=5}
#ap2g, gdv1, pfs16, etramp10.3, gexp5, pfg14-744, pfg14-748
# m2_seu_jnd <- JoinLayers(m2_seu)

map(stg_mkrs, ~DotPlot(m2_seu_noM12, features = as.character(.x), split.by = "stage_c", group.by = "donor",  
        cols = c("#90bce5", "#ea5bba",  "#4ba7fc", "#f2e48c", "#af1527", "#af1091"
)) + 
  coord_flip()+
  RotatedAxis() +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_x_discrete(labels = names(.x))
)


```


!!!NOTE - RAW COUNTS BEING USED - NEED TO CHANGE TO NORMALISED(DATA) WHICH IS STANDARD
```{r, fig.width=20, fig.height=12}
Idents(m2_seu_noM12) <- "stage_c"

DotPlot(m2_seu_noM12, features = as.character(unlist(stg_mkrs)), split.by = "stage_c", group.by = "donor",  
        cols = c("#ea5bba", "#90bce5",  "#4ba7fc", "#f2e48c", "#af1527", "#af1091"
)) + 
  coord_flip()+
  RotatedAxis() +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_x_discrete(labels = names(unlist(stg_mkrs)))



```